### ISSUE TITLE
Implement File Share Target

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#1009]
This would allow Pinafore to accept images shared from a camera app on Android. https://paul.kinlan.me/file-web-share-target/

**Comment by Krinkle** [comment]
This would also increase the need for a Toot As interface (https://github.com/nolanlawson/pinafore/issues/1808) as the last used instance might not be the one on want to post it to.

**Comment by nolanlawson** [comment]
True, although for now I'm just going to use the most recently-used instance. I'm assuming most folks are only on a single instance, or are primarily on a single instance.
