### ISSUE TITLE
Change "a11y" to "accessibility" in project labels

### ISSUE THREAD

**Issue by Fidgetcetera** [nolanlawson/pinafore#102]
Numeronyms in this format are rather confusing to many people, and there's not much reason I can see that the full word can't be used - there's a "good first issue" label which is longer, and "enhancement" isn't written as e9t. 

I know you've mentioned the project isn't meant to be a full-on project community, but nevertheless people who use pinafore shouldn't have to know or search a semi-obscure tech term to at least see and know an accessibility feature is being worked on (or isn't).

**Comment by nolanlawson** [comment]
Seems reasonable to me!
