### ISSUE TITLE
How to set the default theme

### ISSUE THREAD

**Issue by jeroenpraat** [nolanlawson/pinafore#1086]
How to set the default theme for a Pinafore instance?

**Comment by nolanlawson** [comment]
Take a look at how cybre.space did it. You can change the `DEFAULT_THEME`, `DEFAULT_LIGHT_THEME`, and `DEFAULT_DARK_THEME` constants: https://cybre.tech/cybrespace/pinafore/commit/243f0fd71dbd93c984551f7ffe3e201083069bc3

Relevant code here: https://github.com/nolanlawson/pinafore/blob/30048a7f1227fd9a8137c4d1e7615821dab7b662/src/routes/_utils/themeEngine.js#L5-L7
