### ISSUE TITLE
weird behavior of the emoji picker and custom emoji

### ISSUE THREAD

**Issue by Lonsfor** [nolanlawson/pinafore#1101]
the emoji picker does some weird stuff when hovering over a custom emoji

![Peek 2019-03-16 20-56](https://user-images.githubusercontent.com/15758649/54483205-43ddd480-4847-11e9-8a1a-4150865bac27.gif)

**Comment by nolanlawson** [comment]
This is related to #844 but I think there is some stuff we can do here to at least make the "light mode inside of dark mode" look okay.
