### ISSUE TITLE
Development guide needs updates

### ISSUE THREAD

**Issue by rugk** [nolanlawson/pinafore#1104]
[Here](https://github.com/nolanlawson/pinafore/blob/master/CONTRIBUTING.md#running-integration-tests) it's missing a space and also links to the old Mastodon GitHub docs.

And regarding https://github.com/nolanlawson/pinafore/blob/master/CONTRIBUTING.md#user-content-inferno-is-loaded-dynamically, you also use preact now, not inferneo: https://github.com/nolanlawson/pinafore/commit/13792aef66731c2621e08e04ae02f78163755a5d

**Comment by nolanlawson** [comment]
Thanks for reporting!
