### ISSUE TITLE
Firefox v66 can't load more items in the infinite list

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#1107]
Scroll to the bottom of the timeline, and nothing happens. Repro'd in Firefox v65 on Android, seems to work in v65.

**Comment by nolanlawson** [comment]
Looks like `virtualList._state.scrollTop` is just not getting set to a high-enough value. Not sure what's causing this.

**Comment by nolanlawson** [comment]
Filed a bug on Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1536717

**Comment by PurpleCodingWizard** [comment]
I don't seem to have this issue. It loads old toots, boots without issue in the federated, local and even the lists. Unless, this is about a different infinite list.

The link you posted in bugzilla shows 2275px on Firefox and 2223.5px and on a webview based browser.
My Firefox version 65.0.1

**Comment by nolanlawson** [comment]
I tested this on a OnePlus 5T running Android 8.1.0 in standard Firefox 66.0, not a WebView-based browser. The issue is indeed that when you scroll to the bottom, more toots don't load.

I mistakenly reported this as Firefox 65, but actually it's a Firefox 66 issue (the one that was just released).

**Comment by nolanlawson** [comment]
This bug does not seem to reproduce in Firefox 66 on Ubuntu, only on Android.

**Comment by nolanlawson** [comment]
This is reported fixed in Firefox v67 , and I can't find a workaround, so I'm going to close it.

**Comment by nolanlawson** [comment]
Firefox 67 will be released on May 14th. https://wiki.mozilla.org/Release_Management/Calendar
