### ISSUE TITLE
Card look and feel for different information

### ISSUE THREAD

**Issue by sgenoud** [nolanlawson/pinafore#1136]
As related to #1135, as well as a private discussion let's discuss what are the different possibilities of information present:

- [x] title, image and description (or provider name) (case a)
- [x] title, description (or provider name) –  image missing (case b) #1135 
- [ ] title, image – description (or provider name) missing (case c)
- [ ] title only – description (or provider name) and image missing (case d)

Do we agree on the case b?

For the case c, I would propose two different solutions. Either put the domain if there is not provider name (so there is always a description text) or just hide the image.

Personally I do not mind the title only case if the data is empty, but there might be other opinions?

**Comment by nolanlawson** [comment]
On case b I agree. For case c I propose we just put the domain there, since the image usually looks nice.

For case d I would do the same thing - just put the domain. The reason I say this is that a title without an image or description looks very odd and out of place - it's just the title.
