### ISSUE TITLE
Modal dialogs are too wide sometimes

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#1151]
I think this happened because of #1138. Ideally these modals should be smaller to fit the content.

![Screenshot from 2019-04-13 18-01-47](https://user-images.githubusercontent.com/283842/56086954-52071c80-5e16-11e9-84fc-0f6af530e0e5.png)
![Screenshot from 2019-04-13 18-01-52](https://user-images.githubusercontent.com/283842/56086956-53d0e000-5e16-11e9-91d9-83f77657174e.png)

**Comment by sgenoud** [comment]
It seemed nicer to only have one size of modal -  the smaller ones seemed crammed to me (but it is probably just subjective.

![Capture d'écran 2019-04-15 08 28 20](https://user-images.githubusercontent.com/263325/56111566-b7632680-5f58-11e9-8340-cc2dbd5474f8.png)

**Comment by nolanlawson** [comment]
I wish we could figure out how to have them truly fit their content, but I've messed up the CSS enough that it's tough to get back there.

Personally I'm not 100% happy with either solution, but I really don't like when some of the modals are too wide... just subjective though. :)
