### ISSUE TITLE
Closing dialog returns to the previous page

### ISSUE THREAD

**Issue by charlag** [nolanlawson/pinafore#1159]
Hi! Thanks for the awesome Pinafore!

I'm sorry (and reluctant - I know what a pain it is) to report another bug with navigation.

Here are steps to reproduce:

- Press C to open new status editor dialog
- Click on the profile picture (dialog is not closed at this point)
- Try to close the dialog

Expected:
I am on the profile page

Actual:
I am back at the original page

UserAgent:
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

I would try to fix it myself but I know you've spent some time on this so maybe you know better.

**Comment by charlag** [comment]
Ah, and I completely forgot to mention, it's dev.pinafore.social, not the stable one

**Comment by nolanlawson** [comment]
I think we should just not make the profile picture clickable in that case. It doesn't make much sense anyway.

**Comment by charlag** [comment]
I would kindly ask you to not take it away - that's pretty much the only fast way to open my profile with keyboard (to continue thread or something). Maybe we could add another way of course.

**Comment by nolanlawson** [comment]
OK. Maybe we can close the modal and then navigate.

**Comment by charlag** [comment]
That would be about perfect!
