### ISSUE TITLE
"Always / Never mark media as sensitive" text is misleading

### ISSUE THREAD

**Issue by deutrino** [nolanlawson/pinafore#1215]
In Mastodon there is an option called "Always mark media as sensitive" which, correct me if I'm wrong, marks *outgoing* media as sensitive - it has to do with sending posts, not display of posts. The use of the word "mark" in this text further implies that, in my mind. Yet in Pinafore these options seem to control the *display* of media, not the posting of it. I believe this is misleading, particularly since they are so closely worded to a Mastodon feature which behaves differently.

**Comment by nolanlawson** [comment]
Good point. How about "Show all media by default" and "Hide all media by default" ?
