### ISSUE TITLE
[Feature] Add I2p Instance

### ISSUE THREAD

**Issue by oijkhg** [nolanlawson/pinafore#1263]
**Feature**: Add I2p Instance.
**Why?**: Mainly for better privacy and security but also to support decentralized web communications.

**Related Links**:
https://www.invidio.us/watch?v=2ylW85vc7SA

https://geti2p.net/en/about/media

https://geti2p.net/

https://www.wikipedia.org/wiki/I2p

**Comment by nolanlawson** [comment]
Hmmm, I think this is probably out-of-scope for this project? Right now the goal is to support (most) servers that implement the [Mastodon server-to-client API](https://docs.joinmastodon.org/api/rest/accounts/), such as Mastodon and Pleroma. This seems to be a completely different kind of project that implements a completely different API? Thanks for the suggestion, though!

**Comment by oijkhg** [comment]
@nolanlawson My feature is to enable users to access the Pinafore web UI via I2p.
