### ISSUE TITLE
Push subscription state is shared across instances

### ISSUE THREAD

**Issue by amyspark** [nolanlawson/pinafore#1274]
At present, Pinafore maintains a single source of truth for the push subscription state, as a LocalStorage object named `store_pushSubscription`:
```json
store_pushSubscription:"{"server_key":"snip","id":"72","endpoint":"https://updates.push.services.mozilla.com/wpush/v2/snip","alerts":{"reblog":true,"mention":true,"follow":true,"favourite":true}}"
````
I think this is incorrect, as I can have multiple instances with different configurations.

**Comment by nolanlawson** [comment]
You are correct; this looks like a mistake.

**Comment by nolanlawson** [comment]
Actually on second thought, can a Service Worker even have more than one push subscription? I don't think it can.

/cc @sorin-davidoi

**Comment by amyspark** [comment]
No, it cannot, you're correct. But each instance can send different types of notification (as configured in the corresponding panel).

**Comment by nolanlawson** [comment]
Indeed, it seems you can only have one: https://developer.mozilla.org/en-US/docs/Web/API/PushManager#Methods

> A new push subscription is created if the current service worker does not have an existing subscription.

In that case, we should warn the user if they try to subscribe to more than one. Unfortunate limitation.

**Comment by nolanlawson** [comment]
@amyspark I don't believe different instances can subscribe to different kinds of notifications. Each push subscription is just a bag of alert types.

However different instances can filter notifications differently, and that is handled separately from push notifications and should be correct already.

**Comment by sorin-davidoi** [comment]
I don't think there is something preventing up from sending the same push endpoint to different instances. If we move from storing the subscription on a per-instance basis (e.g. `store_pushSubscription_${instance_domain}`) then is should work.

**Comment by nolanlawson** [comment]
@sorin-davidoi I think that would make the most sense, yes. Something like this:

- you set up push notifications for instance A
- the data is forever tied to instance A
- when you switch to instance B, the push settings provide a warning that you can only have push set up for one instance at a time. You can switch to instance B, but that will delete instance A's push settings.

**Comment by sorin-davidoi** [comment]
> you can only have push set up for one instance at a time

I don't think this restriction is necessary, but not having it will make things confusing:
 - What happens if you are on instance A and you receive a notification for instance B? Is an automatic switch performed when the notification is clicked?
 - The notification needs to display the instance it's coming from.

**Comment by nolanlawson** [comment]
Yeah there's no easy way to do this well.

> I don't think this restriction is necessary

I checked the MDN docs on Service Worker, and it seems that you can only have one PushManager at a time: https://developer.mozilla.org/en-US/docs/Web/API/PushManager#Methods

**Comment by sorin-davidoi** [comment]
Yes, but we can send the endpoint of that singleton/unique PushManager to multiple instances. We would run into the issues mentioned above though, so it might not be worth it.

**Comment by nolanlawson** [comment]
@sorin-davidoi Would this require running a service, though? Right now Pinafore is client-side only and I intended to keep it that way; as hosted, it's actually a collection of static HTML/CSS/JS/image files.

**Comment by sorin-davidoi** [comment]
@nolanlawson Don't think a service would be needed.

High-level overview of how this _might_ work:
 - We get _one_ subscription endpoint from the browser (same as current behavior)
 - We send this subscription endpoint to multiple instances (e.g. `toot.cafe` _and_ `malfunctioning.technology`) - there is nothing preventing us from doing this from what I can tell
 - When we receive a notification we need to show which instance it's coming from (in the title?).
 - When the user clicks on the notification we need not only to open a new tab _but also switch the active instance_ to the one the notification is coming from

**Comment by nolanlawson** [comment]
@sorin-davidoi This makes perfect sense. I'll open a new issue for that. Thanks!
