### ISSUE TITLE
Image attachments and polls are mutually exclusive

### ISSUE THREAD

**Issue by sorin-davidoi** [nolanlawson/pinafore#1275]
The Mastodon UI doesn't allow this, while in Pinafore this currently results in the API rejecting the post.

**Comment by nolanlawson** [comment]
So you're not allowed to create a poll with an image? Then yeah we should not allow this when composing a new toot.

**Comment by nolanlawson** [comment]
Apparently Pleroma does allow this, so I think we should just let the server throw an error if it's not supported.
