### ISSUE TITLE
@username suggestion box crashing the web app

### ISSUE THREAD

**Issue by strypey** [nolanlawson/pinafore#1279]
I'm using Pinafore.social in the "Fennec F-Droid" distro of Firefox (v66.0.4), on two Android devices running Android 4.x. Whenever I start typing @username and the suggestion box pops up, the app crashes. It doesn't seem like the browser crashes, but it is thrown into the background, and I'm returned to my home screen. AFAICT pages in other tabs are unaffected, but Pinafore.social reloads when I refocus on the browser. Maybe related to #478 in some way?

**Comment by nolanlawson** [comment]
Does this repro on latest Firefox?

**Comment by nolanlawson** [comment]
BTW I use Firefox on Android myself to access Pinafore, and I've never seen this. I use regular Firefox, not Fennec.

**Comment by strypey** [comment]
Is "regular Firefox" available via F-Droid? AFAIK I have the latest version of Fennec available for my device, but I have an issue with automated updates on F-Droid on both my devices. I have to toggle the repos off and on every now and then to get updates. I'll try that and get back to you.

**Comment by nolanlawson** [comment]
Regular Firefox is not available via FDroid. Check out FFUpdater in FDroid which can give you the actual Firefox.

**Comment by nolanlawson** [comment]
BTW I use Firefox on Android myself, I'm on version 67.0.3, and I cannot repro.

**Comment by strypey** [comment]
I've toggled the F-Droid repos off and on and updated Fennec. Problem solved ;)
