### ISSUE TITLE
Official docker images?

### ISSUE THREAD

**Issue by pwFoo** [nolanlawson/pinafore#1284]
Hi,
is a official docker image available? Would be nice if an image is built with each new release and pushed to docker hub.

**Comment by nolanlawson** [comment]
I don't plan on publishing an official Docker image right now. I don't know enough about Docker to support this, plus I have an inherent uneasiness toward any central repository (hence why Pinafore is not on the App Store or Play Store; GitHub is an exception). Thanks for asking! :)
