### ISSUE TITLE
Static pinafore client?

### ISSUE THREAD

**Issue by pwFoo** [nolanlawson/pinafore#1287]
I found that issue #27. Is it right that pinafore client could running static with `npm run export`?

I build / run pinafore inside of a docker container, but would be nice to have it static instead of node server based. So I could run the command above to save a static version of the client with all things needed to run it? service worker, scripts?

**Comment by pwFoo** [comment]
https://github.com/nolanlawson/pinafore/blob/master/README.md#exporting

**Comment by pwFoo** [comment]
@nolanlawson 
export fails. Any idea why and how to fix? It's inside of a dockerfile.
```
Step 7/9 : RUN  yarn run export
 ---> Running in 34828e3675c9
yarn run v1.16.0
$ cross-env NODE_ENV=production run-s export-steps
$ run-s before-build sapper-export print-export-info
$ run-s build-template-html build-assets
$ node -r esm ./bin/build-template-html.js
/opt/bin/build-inline-script.js:1
Error: Cannot find module '../src/routes/_static/themes'
Require stack:
- /opt/bin/build-inline-script.js
- /opt/bin/build-template-html.js
    at Object.<anonymous> (/opt/bin/build-inline-script.js:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-template-html" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "before-build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "export-steps" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn run export' returned a non-zero code: 1
```

**Comment by nolanlawson** [comment]
You probably need to run `yarn build` first.

Also FWIW Pinafore is fully static now, even when you just run `yarn build` and `yarn start`. See `server.js` for how it works.

I don't recommend rolling your own static server, though, since you need to set CSP headers yourself and that's an important security feature.

**Comment by nolanlawson** [comment]
See #1290, I've updated the docs on exporting

**Comment by pwFoo** [comment]
I don't know how to set CSP headers and if needed special dynamic routes. Routes not generated to match the static files? Or what do you mean?
It's easy to set headers like `Content-Security-Policy`, but I don't know which value is to set?

**Comment by Oreolek** [comment]
@nolanlawson you still didn't list the routes.

I'm hosting static pinafore with this CSP header:

```
add_header "Content-Security-Policy" "connect-src 'self' wss://[instance url] [instance url];script-src 'self' 'unsafe-inline' 'unsafe-eval'; worker-src 'unsafe-inline' 'unsafe-eval' 'self'; object-src 'none';img-src 'self' 'unsafe-inline' 'unsafe-eval'; default-src wss://[instance url]; data: 'self' 'unsafe-inline' 'unsafe-eval' [instance url]";
```

**Comment by pwFoo** [comment]
Hi @Oreolek 
"[instance url]" is for example "mastodon.social" I think? So I would need to hardcode it to the webserver. Fine for my own instance, but how it works if I add / change the instance in pinafore?
Or I'm wrong how CSP works?

**Comment by Oreolek** [comment]
that's why it's a static copy - it doesn't manage CSP headers, you set them up in the webserver. If you add a new instance, you have to allow it in CSP or the browser won't connect. Not okay for a public instance, should be fine for a single account.

**Comment by nolanlawson** [comment]
@pwFoo That's the point; the CSP headers are dynamically generated and will change with each build, so you wouldn't be able to set them yourself.

@Oreolek Inside of your CSP you have `script-src 'unsafe-inline'` which would allow any rogue Mastodon instance you connect to using Pinafore to embed arbitrary scripts on your page, including reading local data from other Mastodon instances. This is basically the worst kind of thing that CSP is intended to block, and it's exactly why I don't intend for people to run it themselves. [Mozilla Observatory](https://observatory.mozilla.org) can give more details.

If you really, really want to solve this problem, then we would need to have a build step that could convert the current generated `now.json` into Nginx/Apache config files or whatever you're using.

**Comment by pwFoo** [comment]
@nolanlawson
Thanks for explain it here!

**Comment by Oreolek** [comment]
@nolanlawson first, pinafore doesn't work without the "unsafe-eval" or "unsafe-inline" instructions and second, it's for a specific instance that I do trust.

**Comment by nolanlawson** [comment]
@Oreolek If you're only connecting to an instance that you trust, then yes, it should be fine to use unsafe-eval/unsafe-inline. Because of federation, though, you also need to trust that it's correctly sanitizing any content from _other_ instances, but... Mastodon does seem to do a good job of this. :)
