### ISSUE TITLE
Cannot mark media as sensitive when a toot has no content warning

### ISSUE THREAD

**Issue by Aldarone** [nolanlawson/pinafore#1297]
I can't find the « mark as sensitive » button for uploaded media but I found people making reference to it.

Perhaps it's aregression, perhaps it's my broken brain ? :confused: 

![Screenshot_2019-07-04 ltch fr · Home(1)](https://user-images.githubusercontent.com/2682011/60688452-7888a100-9eb5-11e9-95f6-acdc2565b070.png)

**Comment by nolanlawson** [comment]
Thanks for opening the issue! This is a deliberate design decision in Pinafore. To mark media as sensitive, you also have to add a content warning to help explain why it's sensitive. It also keeps things simpler because we only need one button. :)

**Comment by Aldarone** [comment]
I'm guessing I'm gonna be a pain in the ass by questionning something that has been decided a long time ago then. 

While I understand your decision (and I acknowledge that you decided to enforce by design what is already a current practice on the fediverse) I find that it needlessly complexify the act of viewing the uploaded media for "my" followers.

Let's say I'm a huge selfie poster. The sensitive thing to do is to mark the selfie as sensitive and tell people that there is eye contact in this picture.

More often than not I don't have anything more to say so the content of my toot would be something like « Feeling pretty today [CW Eye Contact] » with the attached selfie. People see the toot, click on the mask and can see my beautiful face.

If I **have** to use the CW functionality, things would go like this : There would be a CW with « selfie, eye contact », the content of the toot would be hidden even though it does not contains anything triggering (« Feeling pretty today ») and the attached selfie. Now people have to click on « Show more », they see a non triggering text content that doesn't need to be hidden in the first place and they finally click on the mask and see my beautiful face.

That's two clicks instead of one for every toot in the case where only the media can be triggering and the toot text is absolutely not. And toot after toot, it can add up to a considerable number of unnecessary click per day.

I won't insist more anyway, you probably have had this debate some time ago when you took this decision but let me know what you think about my explanation. :slightly_smiling_face:

**Comment by Aldarone** [comment]
Maybe a solution would be to keep the interface this way (one button then) but if there is a CW and a media but no text content, pinafore would copy the CW text in the toot content, disable the CW and mark the media as sensitive ?

**Comment by nolanlawson** [comment]
Actually this has not been discussed much before. :) I made the decision early on, and nobody really asked me to change it until now.

I think your use case is valid. Maybe there is some way that the Pinafore UI could adapt if there is a CW and media but not text content. For instance, when you click the "show more", it could automatically show the picture as well. This would only help for your followers who use Pinafore, though.

**Comment by nolanlawson** [comment]
Reopening as this is a reasonable request and I have to meditate on it a bit. The challenge is to not make the UI too complicated for 99% of users in order to satisfy 1% of users (because if I did that for every 1% use case then the UI would quickly get too overwhelming, and the whole goal of Pinafore is to be as "simple" as possible).

However it's worth noodling on; there may be a good compromise here.

**Comment by Aldarone** [comment]
I'm not using Mastodon anymore but many thanks to you <3
