### ISSUE TITLE
Opening the overflow menu on ones own profile opens an empty menu

### ISSUE THREAD

**Issue by codl** [nolanlawson/pinafore#130]
![2018-04-15t13-49-58-0o0o](https://user-images.githubusercontent.com/315139/38778106-071a33a4-40b4-11e8-852c-7111969ac31d.png)

**Comment by nolanlawson** [comment]
Hmm I could put "mention" there, even though it's odd to mention yourself. The only other reasonable option is "edit profile," which is not implemented yet (#6).

**Comment by codl** [comment]
you could not show a menu button? at least until edit profile becomes a thing

**Comment by nolanlawson** [comment]
That may mess up the layout. I'm happy to just add "mention" for now. :)
