### ISSUE TITLE
Provide an example of user instance address in placeholder?

### ISSUE THREAD

**Issue by marataziat** [nolanlawson/pinafore#1332]
https://pinafore.social/settings/instances/add we should show an example of how user need to fill instance name and stuff! Like 'testuser@somedomain.tld' instead of just "enter instance name"!

**Comment by nolanlawson** [comment]
Is this okay?

![Screenshot from 2019-07-12 07-51-39](https://user-images.githubusercontent.com/283842/61137198-f03c6a00-a479-11e9-97a0-33e527c804ab.png)

**Comment by marataziat** [comment]
yeah, I thought that I need to enter something like @username@instance.tld :)
