### ISSUE TITLE
Use the `text` field of a toot when using delete/redraft

### ISSUE THREAD

**Issue by Aldarone** [nolanlawson/pinafore#1339]
Since Mastodon 2.9.0, [the unformatted content of the deleted status is available in the server reply](https://github.com/tootsuite/mastodon/commit/6d44f2441bf2aa14d11e481d9d2cfe82a74d81ed) when one deletes a toot. This has been done to help clients to implement the delete/redraft feature.

Pinafore could now simply check if there is a field named `text` in the json sent when deleting a toot to fill the redraft modal, removing the need to parse the rendered html content.

It would be beneficial to glitch-soc and pleroma users since when they use extra formatting, some of the html tags are stripped and do not appear in the redraft modal (stuff like ul, ol and blockquote)

**Comment by nolanlawson** [comment]
Good to know, thank you! This also makes the delete/redraft implementation simpler.
