### ISSUE TITLE
Avatars sometimes show gray background even while online

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#1344]
I think this happens sometimes when network requests intermittently fail? I guess it would be better to retry to load the image, or else use [native image lazy loading](https://addyosmani.com/blog/lazy-loading/) when that's available.

**Comment by nolanlawson** [comment]
For the record, I observe this in Firefox. It seems to occur when I open a tab that I haven't looked at in a while?

**Comment by nolanlawson** [comment]
So oddly since Firefox support `Image.prototype.decode()` now, the issue is apparently that [this promise](https://github.com/nolanlawson/pinafore/blob/4bd181d3ccfd768d4ad350e8194acc53912b79e1/src/routes/_utils/decodeImage.js#L3) never resolves? Otherwise it would show the "missing" avatar, not the gray "loading" background.

**Comment by nolanlawson** [comment]
Apparently this is the Firefox bug. We should disable image.decode() in Firefox until it's fixed. https://bugzilla.mozilla.org/show_bug.cgi?id=1565542

**Comment by sorin-davidoi** [comment]
The bug was fixed in [68.0.2](https://www.mozilla.org/en-US/firefox/68.0.2/releasenotes/).
