### ISSUE TITLE
Feature Request: Hide replys (optional)

### ISSUE THREAD

**Issue by GambaJo** [nolanlawson/pinafore#1363]
It would be nice, if I can hide the replys in my TL (like in Mastodon itself, look at the screenshot).
![29-07-_2019_13-40-32](https://user-images.githubusercontent.com/1378907/62045785-90c6b400-b206-11e9-97a6-3875b587cc05.jpg)

**Comment by nolanlawson** [comment]
This is available in the instance settings. :) Go to:

- Settings
- Instances
- (instance name)
- Home timeline filters
- Untick "show replies"
