### ISSUE TITLE
mastodon send more notifications than pinafore

### ISSUE THREAD

**Issue by pwFoo** [nolanlawson/pinafore#1366]
Looks like pinafore send only the first notification? mastodon web client send all notifications.
Sometimes it would be better to get more than one notification because it could be reply, mentioned and favorited and I could miss one if there isn't a notification (android bar).

**Comment by pwFoo** [comment]
Some time it looks like mastodon send push notifications to android device, but pinafore not. Maybe dependent on notification type? Some updates I would miss if I not additionally would get the mastodon web client push notification on same device. Both used as chrome for android "app" (via add to homescreen).

**Comment by nolanlawson** [comment]
Which browser and OS is this?

**Comment by pwFoo** [comment]
Most of the time mobile. OnePlus 5
- Chrome for Android
- Android 9 (OxýgenOS 9.0.7)

**Comment by pwFoo** [comment]
Updated pinafore to latest / 1.11.6.

**Comment by pwFoo** [comment]
I close that issue. Think it is dependent on #1364
