### ISSUE TITLE
viewing an image in a thread jumps to top of thread

### ISSUE THREAD

**Issue by abochmann** [nolanlawson/pinafore#1374]
When opening an image a few posts down in a thread, the view jumps back to the top after closing the image (either by pressing ESC or by clicking the close button).

Pinafore 1.11.7

Doesn't happen with all image posts, but it's reliably reproducible in my local Pinafore installation with Firefox 68.0.1 when using the thread that starts with this post: https://witches.live/@anna/102572207621954938 (get post via search, open thread from there, scroll to bottom, click on last image - closing the image goes back to the top of the thread).

**Comment by nolanlawson** [comment]
Thanks for the bug report! Unfortunately I can't seem to reproduce locally on Firefox 68.0.1 on Ubuntu, even using the provided instructions. :confused: 

Here are my steps:

1. Click Search
2. Enter https://witches.live/@anna/102572207621954938
3. Click the toot
4. Scroll to the last image in the thread
5. Once the modal is opened, press Esc

It doesn't seem to scroll back to the top...

**Comment by abochmann** [comment]
I can't seem to reproduce the behaviour with Pinafore 1.12.2 and Firefox 69.0 either, so I'll close this issue.
