### ISSUE TITLE
Intermittent (but frequent) "Internet request failed. Showing offline content"

### ISSUE THREAD

**Issue by ieure** [nolanlawson/pinafore#1382]
Probably at least every other day, I run into an issue where I load Pinafore and I get an "Internet request failed. Showing offline content" error.  Reloading the page produces the same error.

If I go to mastodon.social (where my account is), it works fine.  While I'm not 100% sure, visiting mastodon.social then reloading Pinafore seems to fix it, but I don't know if it's related or just how the timing works out.

It seems to be related to these errors in the console:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://mastodon.social/api/v1/timelines/home?limit=20. (Reason: CORS request did not succeed).
Failed to load ‘https://mastodon.social/api/v1/timelines/home?limit=20’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: NetworkError when attempting to fetch resource.’.
TypeError: "NetworkError when attempting to fetch resource."
```

In a tab which fails to load, there are several CORS errors, and the request to `/timelines/home` doesn't appear in the network log.  In a tab which loads successfully, I don't see CORS errors and I see the request to `/timelines/home`.

**Comment by ieure** [comment]
Additional data: A tab I had Pinafore open in *persistently* fails.  Reloading shows the same error.  But if I open a new tab, it works.  The working tab keeps working on reload, and the broken one stays broken.

**Comment by sorin-davidoi** [comment]
![image](https://user-images.githubusercontent.com/2109702/62825430-b317e480-bbab-11e9-932b-ab4048e32b37.png)

**Comment by ieure** [comment]
Yep, that's pretty much what I see as well.

**Comment by nolanlawson** [comment]
Hmm both `mastodon.social` and `toot.cafe` should have `Access-Control-Allow-Origin:*` which should allow CORS requests to succeed. Maybe this is an issue with the browser or with an extension like Privacy Badger?

I know that Firefox has recently been playing around with heuristics to block "third-party trackers." Almost inevitably this means blocking cross-origin requests, which Pinafore relies on to work properly. (In other words, Firefox may think that `mastodon.social` or `toot.cafe` are "third-party trackers.")

Did you change this setting in Firefox?

![Screenshot from 2019-08-11 11-23-04](https://user-images.githubusercontent.com/283842/62837941-6b846d80-bc2a-11e9-8450-b7afddb8daa4.png)

**Comment by ieure** [comment]
Yes, I have it set to Custom, blocking fingerprinters, trackers, and miners.  I'd think that the behavior would be more consistent, rather than sometimes breaking, but working if I open a new tab.

**Comment by sorin-davidoi** [comment]
I've set it to Custom as well (blocking everything) and running uBlock Origin on top (default settings).

**Comment by nolanlawson** [comment]
OK, please let me know if you can repro in a vanilla version of Firefox with the default settings. Unfortunately it looks like the Firefox "custom" settings don't allow you to whitelist any sites (you would need to whitelist the instance you want to connect to, as well as possibly pinafore.social), so unfortunately I don't know of any ways to fix this other than to stick with the "standard" settings.

Closing as this appears to be a browser-specific issue rather than a Pinafore specific issue.
