### ISSUE TITLE
Web app functionality not working as expected on iPad.

### ISSUE THREAD

**Issue by djoerd** [nolanlawson/pinafore#1386]
When using Safari’s “put of Home screen” option, my iPad pro opens Pinafore in a browser tab (showing the url bar) instead of as a stand alone app. It does work on for instance: start.duckduckgo.com.

**Comment by nolanlawson** [comment]
What version of iOS is this? We purposefully block "add to home screen" functionality (as a PWA, as opposed to a browser tab) on iOS <12.2 because of bugs in iOS.

**Comment by djoerd** [comment]
Sorry for the late responsie: I am on iOS 12.4. The Twitter app works well too.

**Comment by nolanlawson** [comment]
I cannot reproduce on an iPod Touch running 12.4.1. You may need to remove the current icon from your home screen in order for it to work. Also you may have to log in again, but it should render the app without the URL bar.

**Comment by nolanlawson** [comment]
I.e. remove the app from the home screen, go to Pinafore in Safari, then add it to the home screen again, and the second time it should work. Let me know if that helps!
