### ISSUE TITLE
OffscreenCanvas convertToBlob() is slow in Chrome

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#1396]
I've tested on both Linux and Android, and Chrome seems to take around 500-700ms to run `convertToBlob()` on an `OffscreenCanvas`. I've tried a few different techniques and can't seem to get it any faster.

We may just have to disable `OffscreenCanvas` for now. Using the other method (canvas on main thread, decode in worker thread) results in about 100ms round-trips which is much faster.

https://github.com/nolanlawson/pinafore/pull/1391#issuecomment-522271375

/cc @sorin-davidoi

**Comment by sorin-davidoi** [comment]
Not even changing the type to `image/jpeg` and the quality to `0.1` seems to make a difference.

**Comment by nolanlawson** [comment]
I filed a bug on Chromium about this: http://crbug.com/995099

**Comment by nolanlawson** [comment]
fixed in #1398 , we are UA-sniffing Chrome for now to avoid this API
