### ISSUE TITLE
Sometimes new statuses/notifications don't show up

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#14]
Sometimes new statuses and notifications don't appear until you refresh. Not sure how this happens, but I think it may be related to the browser suspending background tabs.

**Comment by spriteclad** [comment]
Thought I might as well throw what happened to me in the ring -- turns out my adblocker (uBlock Origin's EasyPrivacy list) was blocking all WebSocket requests from any external domain ending in `.space`. Yeeeaaah. Might want to either disable your ad blocker if you're also using Awoo and EasyPrivacy.

**Comment by nolanlawson** [comment]
Based on testing in Firefox and Chromium, this appears fixed at least insofar as when you come back to the app after a long period of time the notifications appear, and you don't need to refresh. So probably either #1196 or #1195 (or both) fixed it.

**Comment by nolanlawson** [comment]
Still not fixed, Chromium on Android

**Comment by nolanlawson** [comment]
Still not fixed, according to a Chrome on macOS user. "I've gotten used to refreshing to make sure I see my notifications."

**Comment by nolanlawson** [comment]
This is *still* happening. I just repro'd it on my wife's machine in Chrome.

What happened was this:

1. During the "active" state transition in lifecycle.js, the `this._ws` (websocket connection) was defined, and its `readyState` was [`WebSocket.OPEN` (1)](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket). So we didn't bother trying to reconnect. However, the websocket connection was not actually open... >_<

**Comment by githubetc** [comment]
Just confirming that same "no auto refresh" bug is still happening with Pinafore version 1.14.0 on Chrome Android and Chrome MacOS.

Notifications are OK, got them almost instantly, it is just that the statuses do NOT show up on the timeline automatically. So I have to keep clicking refresh after hearing each the notification.

**Comment by nolanlawson** [comment]
Can't consistently repro this, and it may be a bug in Mastodon itself. If I can get a consistent repro, then I'll look into it.
