### ISSUE TITLE
Disabling blurhash in settings is broken

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#1421]
Regressed by #1418, didn't notice until just now.

![Screenshot from 2019-08-21 22-42-53](https://user-images.githubusercontent.com/283842/63488803-1dab0900-c465-11e9-8ab4-c4e5b6c0a12d.png)

**Comment by sgenoud** [comment]
Sorry I did not check that case!

**Comment by nolanlawson** [comment]
No worries, we have way too many options now :stuck_out_tongue:

**Comment by nolanlawson** [comment]
The HTML/CSS can probably be cleaned up a bit. I think we should just treat this option the same as a server that does not support blurhash - the "blurhash" is just a play gray color in that case. Then we don't need special logic for this option at all; the blurhash is just gray.

The added `-transparent` CSS classes seem to have complicated things and are probably my fault. Probably it should all be the same system regardless of blurhash or no blurhash.

**Comment by sorin-davidoi** [comment]
> The added -transparent CSS classes seem to have complicated things and are probably my fault. 

That's my mess, sorry about that!
