### ISSUE TITLE
Tesseract worker should be shut down

### ISSUE THREAD

**Issue by sorin-davidoi** [nolanlawson/pinafore#1447]
![image](https://user-images.githubusercontent.com/2109702/63886143-1b532c80-c9da-11e9-80aa-017377225779.png)

![image](https://user-images.githubusercontent.com/2109702/63886225-4e95bb80-c9da-11e9-83bb-3004de9b1d11.png)

The 13.4 MB stay allocated after the editing modal is closed.

When should it be shut down:
 - After extraction ends?
 - When the compose form has no images (they are either removed or the form is submitted)?

**Comment by nolanlawson** [comment]
It doesn't bother me much that it stays allocated even after extraction ends. I see it a bit like the on-demand modules - they're loaded via `import()`, they consume memory after they're used, but they're gone once you refresh or re-navigate.

We could definitely close down the worker after a delay or something, but I wonder if it's more trouble than it's worth?
