### ISSUE TITLE
Compatibility bugs with Mastodon v3.0

### ISSUE THREAD

**Issue by pwFoo** [nolanlawson/pinafore#1539]
Hi @nolanlawson 
search doesn't work anymore after update to 1.13.0. Also tried to update to 1.13.1 with the same issue.
Each search I get the following error message

![image](https://user-images.githubusercontent.com/333408/65629411-93aa0f00-dfd3-11e9-89c5-7989e533f4dc.png)

**Comment by pwFoo** [comment]
I use it with docker and just mastodon.social

**Comment by nolanlawson** [comment]
Thanks for reporting. The issue here is not Pinafore but rather Mastodon 3.0: https://github.com/tootsuite/mastodon/releases/tag/v3.0.0rc1

There are breaking changes in Mastodon 3.0's search API, as well as other APIs. Pinafore needs to work around those.

**Comment by Booteille** [comment]
Hi. I still have the issue with search.

![Screenshot_2019-10-09 framapiaf org · Search(1)](https://user-images.githubusercontent.com/2203721/66491485-11c9e380-eab3-11e9-807c-4bd0bafb6b65.png)

Tell me if I can help you to debug it somehow.

**Comment by pwFoo** [comment]
I updated today and it works fine again for me.

**Comment by nolanlawson** [comment]
@Booteille You may have to refresh to get the update.

**Comment by Booteille** [comment]
If by "refresh" you mean clicking on "reload" and/or cleaning Firefox site data for Pinafore... I already did it.

**Comment by nolanlawson** [comment]
@Booteille You may have to clear your service worker settings then. Go to `about:serviceworkers`, find Pinafore, and unregister the service worker. Then check that the Pinafore version in Settings -> About Pinafore is v1.15.0. Sorry for the trouble!

**Comment by Booteille** [comment]
I didn't had to unregister the service worker because it now works without I had to do anything.
If I go to `about:serviceworkers` now, I don't find any of it. I am using 1.15.0 now.
So everything is fine now. No worries.

Maybe your answers will help someone else in the future.

Thank you!
