### ISSUE TITLE
Cannot attach photos from iOS

### ISSUE THREAD

**Issue by feld** [nolanlawson/pinafore#1546]
On iOS when you use the camera icon to attach photos / take a photo it opens the File explorer and not the photos app or camera. These are files/documents and not the media stored on the device.

**Comment by nolanlawson** [comment]
Hmm this may be due to the iOS audio fix. There may be no way to fix this without breaking audio uploads.

Is there no way to access photos on iOS this way?

**Comment by nolanlawson** [comment]
Also which iOS version are you using? Safari or home screen app?

**Comment by feld** [comment]
iOS 13, Safari.

There's no way to access photos from the file explorer unless you save your photos to Files instead of to your Photos. Which would be extremely unusual, and not even possible until iOS 13 started giving that as an option.

**Comment by nolanlawson** [comment]
Based on https://toot.cafe/@nolan/102920564401900604 it seems we will have to have separate behavior for iOS 12 and 13 to fix this.
