### ISSUE TITLE
[KaiOS] "SyntaxError: missing = in const declaration" in settings

### ISSUE THREAD

**Issue by saper** [nolanlawson/pinafore#1565]
using Nokia 8110 4G with KaiOS 16.00.17.00

When going to settings tab some JavaScript errors are thrown in the logcat. Top menu icons are no longer displayed on the settings tab - although one can still go left right and select them.

```
10-11 00:13:03.063 32588 32588 E Browser : [JavaScript Error: 
"SyntaxError: missing = in const declaration" {file: "https://pinafore.social/settings" line: 1 column: 647 source: "?void 0:JSON.parse(n):void 0)),e[t]}}),set(e){if(s)for(const[t,n]of Object.entries(e))localStorage.setItem(`store_${t}`,"}]
```

**Comment by nolanlawson** [comment]
The error here is that by default Pinafore uses ES2015+ whereas KaiOS only supports ES5 (with some ES2015 stuff). I have a special build for KaiOS to address this. Once I submit to the KaiStore, you'll actually be able to use Pinafore with KaiOS. :)
