### ISSUE TITLE
[KaiOS] Add instance - "Log in" button remains light blue

### ISSUE THREAD

**Issue by saper** [nolanlawson/pinafore#1566]
using Nokia 8110 4G with KaiOS 16.00.17.00

When navigating to https://pinafore.social/settings/instance/add

I type "mastodon.social" in the instance text box, click KaiOS "Done" button (to end text entry).
Unfortunately, "Log in" button remains light blue and never becomes "darker" and it cannot be pressed.

**Comment by nolanlawson** [comment]
See #1565 - I would expect almost everything to be broken on KaiOS unless it's running in ES5 compat mode (which is a new thing I'm adding just for KaiOS).
