### ISSUE TITLE
can't flag an image as sensitive

### ISSUE THREAD

**Issue by codl** [nolanlawson/pinafore#158]
there's no way to flag an image as sensitive without also setting a cw. or if there is, I couldnt find it

**Comment by nolanlawson** [comment]
I did this as an intentional design decision. I think it's a bit confusing to have two separate settings, and every sensitive image could probably benefit from a CW.

**Comment by nolanlawson** [comment]
I should say I'm open to hearing if there's a use case for this, but my strong feeling is that it makes sense as a single setting. :)
