### ISSUE TITLE
Video backgrounds look wrong sometimea

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#159]
Link: https://cybre.space/@viciousviscosity/99880909241037314

Screenshot:

![screenshot_20180418-084831](https://user-images.githubusercontent.com/283842/38943159-91f1e5a2-42e5-11e8-96ad-9888834a0cd5.png)

**Comment by nolanlawson** [comment]
Chromium on Android BTW

**Comment by codl** [comment]
i've encountered this on desktop chrome as well, for gifs, not videos,  it happens when the video has to be scaled down to fit the screen
