### ISSUE TITLE
Image description window overlaps image

### ISSUE THREAD

**Issue by irfon-kim** [nolanlawson/pinafore#1597]
The blank to enter an image description overlaps the tiny preview of an image, and does so increasingly as you enter text. This is especially bad if you're attempting to describe an image that contains text, and providing a transcription of the text. (For example, if I'm posting a screenshot of a tweet and want to provide the text of the tweet as the alt-text, having the image covered up as I'm entering text requires me to open it a second time elsewhere and flip back and forth.)

**Comment by irfon-kim** [comment]
That works quite well. Thanks for the tip!

**Comment by nolanlawson** [comment]
Thanks for the feedback! :)
