### ISSUE TITLE
Feature request: post to multiple accounts at once

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#161]
Via https://mastodon.mit.edu/@amsomniac/99878031650693112

It's an interesting request, but may require a lot of re-architecting of Pinafore to support, since the current design is that you only have one "current" instance at a time. But I've heard from more than one person that they'd like to have a "concurrent" account experience, e.g. get notifications from two accounts at once. So perhaps it could be folded into that feature request.

**Comment by rodneyrod** [comment]
Maybe this could include multiple account support more broadly?

In my use case at least, having multiple accounts come through in the same feed would be a great feature to have.

**Comment by nolanlawson** [comment]
@rodneyrod That may be worth opening a new issue for. I don't think I'll get to it anytime soon though because it would be a substantial rearchitect. I tend to feel the same way about this issue; it would be very nice, but it just doesn't seem likely given how Pinafore currently works.
