### ISSUE TITLE
Feature request: Direct Message delivery by email

### ISSUE THREAD

**Issue by strypey** [nolanlawson/pinafore#1615]
The net already has a federated system for direct messages. It's called email. While there may be something to be gained by implementing a whole new DM system on top of AP, I'd love to have the option of receiving and replying to DMs via email. Some details on the desired UX:

As a user ... 
1) I'd love to have a user setting that allowed DMs to be sent to the email address associated with my fedi account, instead of (or as well as) appearing as a notification in Pinafore
2) I'd want to be able to choose whether or not someone who uses that feature can see my email address when I DM them, or whether they get a generic noreply or replyto address generated by the instance.
3) I'd love to be able to reply to DMs from an email notification, even when the user has chosen not share their email address with me, the same way I can reply to GH issue comments from email.
4) I'd like to have settings that allowed me to allow DM>email only for users I follow, or only for mutuals.

**Comment by nolanlawson** [comment]
Hi, thanks for opening the issue. For the first one, you can actually configure that in the Mastodon notification settings - you can receive an email anytime you're mentioned (not quite the same as DMs, but it will cover them).

As for the other points, I'm not sure how Pinafore could reasonably solve this problem? Pinafore is purely client-side software, i.e. it only runs in JavaScript in the browser, so it wouldn't be able to send or receive emails. I could add server-side logic, but I've chosen not to for privacy reasons. So I think for most of these points you may want to file an issue on Mastodon instead?

I think these suggestions are valid but are outside of the scope for Pinafore, so closing this issue. Thanks!

**Comment by strypey** [comment]
On 2019-10-31 13:49, Nolan Lawson wrote:
> you can receive an email anytime you're mentioned

Not sure I want to drink directly from that particular firehose ;)

> So I think for most of these points you may want to file an issue on Mastodon instead?

Sounds like it. If Mastodon were to implement the server logic to do
this, then this issue could be revisited, to discuss adding Pinafore
settings to expose it to users.
