### ISSUE TITLE
Tappable and Clickable Space

### ISSUE THREAD

**Issue by Fidgetcetera** [nolanlawson/pinafore#163]
Right now, it's entirely possible, especially on mobile layouts, to have absolutely no on-screen space where a user can tap the screen without causing an action. This can be an issue for people with hand tremors and similar issues (see https://axesslab.com/hand-tremors for an explanation).

I'd suggest an option to place extra spacing between posts, but I'm not sure that's a great fix, because it's entirely possible to have a post take up your entire screen. I'm not totally sure on this idea, but I think it'd be reasonable to make the space to the left of a post beneath avatars be unclickable? There's plenty of space to still click on the post and go to the full view, especially with the timestamp link also sending you there.

**Comment by nolanlawson** [comment]
Hmmmm that's interesting. What about an option to just disable "tap entire status to go to that status"? You can actually still go to the status by tapping on the date, so it technically doesn't lock the user out of any functionality.

That way, the only things that would be tappable are:

- buttons
- text links
- image links

**Comment by Fidgetcetera** [comment]
That sounds like a pretty good plan!

**Comment by MarcoZehe** [comment]
This would also be consistent with the reports screen reader users get from VoiceOver or other screen readers on various platforms, where only links (both text and image) and buttons are considered tapable. Well of course unless you count in the text areas for toots themselves. I never even tried to tap on the status text, always used the time stamp if I wanted to view the thread. Because the text was just text. ;)

**Comment by sorin-davidoi** [comment]
The fact that the entire status is clickable also makes it impossible to select the content - as soon as the mouse click is released the page navigates to the status.

**Comment by nolanlawson** [comment]
I know this is an old issue, but for what it's worth the "I can't select text" issue has now been resolved regardless of whether the "Disable tappable area on entire toot" option is checked or not:

https://github.com/nolanlawson/pinafore/blob/af1bb984c93a4961c12ab92001519a18af963cc0/src/routes/_utils/delegate.js#L24-L30
