### ISSUE TITLE
Pinafore doesn't work with Brave Browser when Shields are Up

### ISSUE THREAD

**Issue by andres-moreno** [nolanlawson/pinafore#1636]
Brave users will have to have their shields down to use Pinafore. Otherwise, the feeds won't populate and the application is unusable.

**Comment by nolanlawson** [comment]
I'm pretty sure this is related to https://github.com/nolanlawson/pinafore/issues/23. Anything that blocks third-party XHRs will need to whitelist those servers (in this case, the Mastodon instance).

**Comment by nolanlawson** [comment]
So e.g. if you connect to `myinstance.com`, then you will have to whitelist `myinstance.com` to tell Brave not to block it.

**Comment by andres-moreno** [comment]
Nolan,

Thanks for getting back to me. There is no way to whitelist domains in
Brave (https://github.com/brave/brave-browser/issues/5290). I'll just turn
my shields down and use Pinafore that way. I have been following you in
Mastodon for a while so I think I know what I am getting into!

Cheers! afm

**Comment by nolanlawson** [comment]
Thanks, good to hear! You may want to submit a feature request to Brave to allow for whitelisting. The only third-party domains that Pinafore will contact are your Mastodon instances; you can check the source code to verify. :slightly_smiling_face:

**Comment by andres-moreno** [comment]
Nolan,

There is already a feature request for Brave to whitelist. I should have
looked into it more before filing a bug on Pinafore. On the other hand,
reporting the issue will save time for Brave users that aren't very
technical.

Cheers! afm
