### ISSUE TITLE
iOS Safari: can't long-press on image to save it

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#1637]
As reported here: https://cybre.space/@SpankyWorks/103138749441227121

I'm pretty sure this works on other browsers/platforms?

**Comment by SpankyWorks** [comment]
Update: it actually works fine in iOS Safari and the error only occurs when used in PWA mode on iOS. I've produced this issue on iOS 13.1.1 and 13.2.2.

**Comment by nolanlawson** [comment]
Does it also happen to the Mastodon frontend when it's in PWA mode? Is this just a general issue with `<img>` tags on Safari in PWA mode?

**Comment by SpankyWorks** [comment]
Looks like it happens on the masto frontend as well. Guessing this is either an iOS PWA bug or there's some special webkit wizardry that allows you to do this in a PWA that nobody knows about.

In any case, doesn't appear to be a pinafore bug so this can be closed. Seems the issue stems from the fact that long-pressing to open a context menu is just not supported for iOS PWAs (which, annoyingly, means you can't read image descriptions in a PWA by long-pressing the image)

**Comment by nolanlawson** [comment]
Thanks, good to know! Sorry that the situation on iOS is so frustrating. Hopefully Apple will fix it soon.
