### ISSUE TITLE
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data TimelineStream.js:57:52

### ISSUE THREAD

**Issue by saper** [nolanlawson/pinafore#1673]
Firefox 69.0.2 (64-bit)

Updated Pinafore from 1b954990 to aa662682 

And unfortunately updated my Pleroma from https://git.pleroma.social/pleroma/pleroma/commit/3b1bc079af8fb6e467a9114de0d32e2de59a7fab to https://git.pleroma.social/pleroma/pleroma/commit/8efacfed677ea2f06ac228294faec77a38060976 and started seeing this:

````
SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data TimelineStream.js:57:52
    onmessage TimelineStream.js:57
    onMessageCallback websocket.js:75
    onMessageCallback self-hosted:1003
````

**Comment by saper** [comment]
Access to the streaming service seems to work: 

      my.ip.add.ress - - [14/Dec/2019:19:04:41 +0000] "GET /api/v1/streaming?stream=user&access_token=sometoken HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; FreeBSD amd64; rv:69.0) Gecko/20100101 Firefox/69.0" "-"

**Comment by saper** [comment]
`e` seems to be `undefined`

**Comment by saper** [comment]
This looks like Pleroma streaming "ping" feature is causing this:

https://git.pleroma.social/pleroma/pleroma/blob/2417b633ed866e6517a3fa0c30d0e85fc76dd548/lib/pleroma/web/streamer/ping.ex#L30

```elixir
  def handle_info(:ping, %{ping_interval: ping_interval} = state) do
    State.get_sockets()
    |> Map.values()
    |> List.flatten()
    |> Enum.each(fn %StreamerSocket{transport_pid: transport_pid} ->
      Logger.debug("Sending keepalive ping")
      send(transport_pid, {:text, ""})
    end)

    Process.send_after(self(), :ping, ping_interval)

    {:noreply, state}
  end
```

Changing the text to be `"{}"` instead causes Pinafore no longer to throw exceptions to the console.

**Comment by saper** [comment]
Thank you. Now it just spits out that warning every few seconds...

**Comment by nolanlawson** [comment]
Is the warning a problem? :)
