### ISSUE TITLE
Bug: Pinafore hangs after 'delete and 'redraft'

### ISSUE THREAD

**Issue by strypey** [nolanlawson/pinafore#1681]
I've noticed for a while that when I 'delete and redraft', I sometimes need to click the post button a couple of times before it actually posts. The button changes from an edit icon to 'post' after the first click, and only posts after the second click. In the last few days, I've noticed that Pinafore sometimes hangs after that second click. The text box empties after I click 'post', but the pop-up doesn't go away. Neither clicking the 'x' button nor clicking outside the pop-up closes it and the only way to get out of it is to reload the page. Screenshot: ![pinafore-screenshot-2019-12-18](https://user-images.githubusercontent.com/313316/71088633-c577df80-2196-11ea-9d62-35cccace2f2c.png).

**Comment by strypey** [comment]
Just happened to me again. After I click the post button, there is an error message saying that its couldn't be posted, due to something about the "parent node". That the error pop-up disappears and the page is frozen and has to be reloaded. When I checked, the error message was in error, and the redraft had, in fact, been posted successfully. I tried to copy'n'paste the error message but I couldn't select the text in the pop-up.

FYI I'm using Firefox 68.0.2 (ABrowser distribution) on Ubuntu 16.04 (Trisquel 8.0 distribution), with NoScript and uBlock Origin.

**Comment by nolanlawson** [comment]
I can't reproduce on Firefox v70 on Ubuntu 18.04. If it happens again, can you open up the Developer Tools (Ctrl-Shift-I) and copy-paste the error message you see?

Also: is there anything in particular about the toot when you do delete-and-redraft? Media images, replies, etc.?

Also, I'm confused about the "toot" button – you say sometimes you have to press the "post button" several times and that the icon changes from an edit icon to post, but those are two different buttons I believe. Or is the button inside of the modal really changing to a pencil (edit) icon?

**Comment by strypey** [comment]
On 2019-12-28 18:24, Nolan Lawson wrote:
> I can't reproduce on Firefox v70 on Ubuntu 18.04.

As with this one, I most often strike the problems I report with
Pinafore when I'm using it with the Fennec F-Droid variant of Firefox on
one of my old Android devices (4.4.4 or 4.4.2):
https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/

I updated it recently, and haven't see the problem since. If it crops up
again, I'll try to follow your instructions.

> Or is the button inside of the modal really changing to a pencil (edit) icon?

Yes, this is quite a common behaviour, but again, I think I mainly
strike it when using Fennec F-Droid. Now that I'm transitioning out of
summer holiday mode and starting to power up my laptop again, I'll keep
an eye out for whether it happens on that too.

**Comment by strypey** [comment]
I'm still intermittently striking this bug. I just ran a test of both GNU/Linux (FF 72 32-bit) and Android (Fennec F-Droid 68.4.1 ESR), posting a new post, then doing delete-and-redraft on it. No issues. I suspect it has something to do with posts that start as replies. I'll test that now. Yup. that seems to be it.

> can you open up the Developer Tools (Ctrl-Shift-I) and copy-paste the error message you see?

Blocked https://pinafore.social/accounts/21439 from extracting canvas data because no user input was detected. blurhash.js:37:51
TypeError: "e.parentNode is null"
    l shared.js:49
    d 13.7a44fd8353440a767430.js:1
    F shared.js:930
    Ue ComposeAutosuggest.html:42
    V shared.js:961
    F shared.js:927
    d 13.7a44fd8353440a767430.js:1
    F shared.js:930
    d 75.fc5011bd41c6dacba462.js:1
    F shared.js:930
    s onCreateDialog.js:8
    a index.js:21
    emit index.js:96
    g ModalDialog.html:175
    _fire a11y-dialog.js:241
    _fire a11y-dialog.js:240
    hide a11y-dialog.js:163
    closeDialog ModalDialog.html:256
    a index.js:21
    emit index.js:96
    s closeDialog.js:5
    onPostedStatus ComposeDialog.html:34
    a index.js:24
    emit index.js:96
    St compose.js:60

**Comment by nolanlawson** [comment]
Looks like the issue is that something is blocking canvas, probably as an anti-fingerprinting measure. Can't tell whether it's Firefox itself or some extension. https://www.reddit.com/r/firefox/comments/ccr33s/firefox_qr_codes_not_showing/

Canvas is only needed for the blurhash feature, so we can probably catch the error in that case and just disable blurhash.

**Comment by nolanlawson** [comment]
FWIW I cannot repro in Firefox v73 on Linux. I do delete-and-redraft on a reply, and everything works fine.

**Comment by nolanlawson** [comment]
Hmmm, nevermind, the canvas issue seems to be a red herring. If canvas is blocked, it seems blurhash is just gracefully disabled. I don't know what's causing this bug.

Unfortunately the stacktrace is minified and it's a royal PITA to un-minify it. Also I cannot repro myself.

**Comment by strypey** [comment]
It happened again today. Definitely seems to be when I redraft replies. Anything else I can do to help you find the bug? Hopefully it will sort itself out when Trisquel updates roll out the Abrowser version of FF 73, but ...

**Comment by poshaughnessy** [comment]
Same issue for me in Firefox 68.6 on Android, using pinafore as a PWA. Here's a video in case helpful:

https://photos.app.goo.gl/wqcQ3mkC2yUqHHEX6

I can try to investigate more later but sorry, just on my phone looking after baby right now! 😄

**Comment by nolanlawson** [comment]
I managed to repro myself on mobile Firefox, but didn't manage to figure out the steps to repro. Thanks for the vid.

**Comment by nolanlawson** [comment]
I can repro only on mobile Firefox 68 on Android using the steps from the video. Firefox Preview and Chrome on the same device are no-repro. I have a fix.
