### ISSUE TITLE
Feature request: avoid auto-tagging users who have used 'mute conversation'

### ISSUE THREAD

**Issue by strypey** [nolanlawson/pinafore#1682]
I'm involved in a thread with about 10 people. As with any thread with that many participants that goes on for long enough, it's going off on various tangents from the original conversation that brought everyone in. Some of the participants may have untagged themselves by using 'mute conversation' at their end, but their addresses are still taking up chars in the text field of each post in the thread. This forces responses to be terser that they might actually need to be to include veryone (forced brevity can increase the chances of miscommunication), as well as making it difficult for new people to enter the conversation if they have something to contribute.

Is there any way for Pinafore, when it responds to a user clicking 'reply', to detect when a user has used 'mute conversation' and avoid copying their address from the previous post into the reply text field?

**Comment by nolanlawson** [comment]
As far as I know, there's nothing in the Mastodon API that allows me to query whether a user has muted a certain conversation. However you could propose this on the Mastodon GitHub seems it seems like something they can change on their end.
