### ISSUE TITLE
POST /api/v1/apps uses JSON instead of form

### ISSUE THREAD

**Issue by charlag** [nolanlawson/pinafore#1692]
Hi, thanks for the awesome Pinafore!

I was playing with one fedi server and I couldn't add Pinafore, POST for apps is failing. It seems like Pinafore is doing a request with JSON body instead of a form. I'm not sure if it's intended on either client or server side, Mastodon docs just mention "Form Data Parameters". I wanted to check if it's intended like that and how it should be.

Thanks.

**Comment by charlag** [comment]
Small update (sorry for spamming it in multiple comments).

It's not only /apps, it's all POSTs with body.
Vanilla client sends JSON, just like Pinafore so probably Pinafore shouldn't change anything.

**Comment by nolanlawson** [comment]
So can this issue be closed? Or is Pinafore doing something different from the default web client?

**Comment by charlag** [comment]
I would check other servers which implement Mastodon API but probably we can close it as it does like an official client.
