### ISSUE TITLE
unable to post toots in older browsers

### ISSUE THREAD

**Issue by nathgit** [nolanlawson/pinafore#1705]
when I try to post a toot, it just pops another box containing my toot, but when I press the button it doesn't do anything. Has anyone else had this issue? I have tried with multiple (old) browsers with the same result. I don't have access to a newer browser right now, but I'll try with it when I do.

**Comment by nolanlawson** [comment]
In general, Pinafore is only designed to worker on newer browsers. Which browsers are you testing on?

**Comment by nathgit** [comment]
I'm using chrome 55 on android 6.

**Comment by nolanlawson** [comment]
The latest version of Chrome is v80, so 55 was released [in 2016](https://developers.google.com/web/updates/2016/11/nic55) and is definitely not supported anymore, sorry.
