### ISSUE TITLE
Implement bookmarks

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#1726]
New feature in Mastodon

**Comment by nolanlawson** [comment]
I mentioned on Mastodon, I'm happy to take PRs, although I worry that this feature would first require that we first fix favorites: #850 

Looking over [the API](https://docs.joinmastodon.org/methods/accounts/bookmarks/), it looks like it doesn't have the same warning as the favorites API about needing to do special behavior for pagination. So maybe bookmarks are just simply sorted by ID? So they might actually be fairly easy to implement.

If you do implement this, I would recommend putting it on the "community" page. As for how to bookmark something, it should probably go in the status context options.

**Comment by charlag** [comment]
i tried it out and, unfortunately, bookmarks work in the same way, with private IDs, it's just that Mastodon docs are half-abandonned.

**Comment by ivan-avalos** [comment]
Bookmarks are basically the only thing stopping me from using Pinafore as my main Mastodon client in both web and mobile.
