### ISSUE TITLE
[Accessibility] Include information about images in long label

### ISSUE THREAD

**Issue by pitermach** [nolanlawson/pinafore#1733]
I'm using pinafore almost exclusively with my screen readers browse mode turned off with the help of the excellent keyboard shortcut support.

One problem I'm running into is that the long label doesn't include any information about media attached to a toot, even if it's described. Sometimes, it's obvious that a toot contains an image at which point I'll switch to browse mode to check whether it has a description, but this isn't always the case.

So, I think the long label for a toot should include information about any attached media. This could come directly after the toot text. A good idea for the format could be something like:
Image/Gif/Video (if there's more than 1 attachment, also number them), a colon so that speech would pause, and if the media has a description, include it next, otherwise say no description.

Knowing if something is a static image or a gif is useful because even if a static image has no description, a blind person would know that they can try to run additional tools on it, like OCR, which might still give a useful result, which isn't anywhere nearly as likely if it's a GIF.

**Comment by nolanlawson** [comment]
Good suggestion! Thanks for weighing in. :)
