### ISSUE TITLE
NVDA gets trapped in autocomplete.

### ISSUE THREAD

**Issue by rkingett** [nolanlawson/pinafore#1736]
On the web app, using the latest version of FireFox and NVDA, I've ran into a bug. When an autocomplete field pops up, editing your status, with NVDA in forms mode, when trying to review the hashtag or username with the keyboard, focus is forced into the autocomplete suggestions and there is no way of staying inside the multiline edit box.

I normally copy the text into notepad and do the editing there before pasting it in, just to avoid that trap again, but I was wondering if there was a way you could loosen the focus grip a little bit?

**Comment by nolanlawson** [comment]
Thanks for filing the bug. I had explicitly tested in NVDA+Firefox when implementing autocomplete, but perhaps something changed in NVDA or Firefox to cause this issue.

When you say "when trying to review the hashtag or username," you mean you are pressing up and down on the keyboard to cycle through the autocomplete options? Also I'm not familiar with forms mode in NVDA; is this something that causes autocomplete not to work? Does it work correctly when not in forms mode?

**Comment by rkingett** [comment]
Forms mode is a mode that's used for typing in edit fields and for navigating a web form. When you navigate to the compose edit field, and hit enter, that high beep you hear means you have just entered forms mode after hitting enter.

No, what I meant was, after typing the hashtag or user name, then pressing left and right to review it, while still in forms mode, yields the following results.

Because keys are being passed through, the interface thinks I want to move to the next element when I want to just review text in that edit box. It seems to happen more when pressing the right arrow key, but sometimes happens when I am pressing the left arrow key.

If a hashtag is typed, while still in forms mode, writing in that edit box, pressing left arrow will cause autocomplete suggestions to pop up. I get stuck reviewing autocomplete suggestions, and have to hit, escape, to go back into browse mode, navigate away from the toot edit box, then navigate back there again, but the autocomplete suggestions still trap me when trying to review my draft toot.

Below is a link on forms mode in NVDA for sighted developers.

https://webaim.org/articles/nvda/#formsmode

**Comment by rkingett** [comment]
After unchecking the first checkbox, left and right arrow keys cycle through the text just fine. I had to uncheck the box that says "left/right keys change focus" setting. Maybe adding some small text that says, may impact screen reader functionality? IDK, but unchecking it solved the problem.

**Comment by nolanlawson** [comment]
Glad to hear, thank you! And yes it should probably be made clear that this is designed for KaiOS devices.
