### ISSUE TITLE
Poll options should be hidden behind content warning

### ISSUE THREAD

**Issue by poshaughnessy** [nolanlawson/pinafore#1766]
Hey Nolan! I created a poll, with a content warning.

I was expecting it to work like it does here on the Mastodon client, i.e. the poll options should not be visible:
https://toot.cafe/@peter/104112384729366704

But using Pinafore, the poll options are visible, even though the rest of the toot is hidden:
https://pinafore.social/statuses/104112384729366704

Is this a bug? :)

**Comment by nolanlawson** [comment]
This is a bug! Thanks. :)
