### ISSUE TITLE
Request: Add ability to disable animated GIF avatars

### ISSUE THREAD

**Issue by aidalgol** [nolanlawson/pinafore#1776]
Profile pictures (aka avatars) can be animated GIFs.  In tootsuite, there is an option to not animate GIF avatars, and only show the first frame statically.  While Pinafore has an option to not autoplay GIFs in statuses/toots/posts, there appears to be no such option for profile pictures.

**Comment by nolanlawson** [comment]
I just tested this out, and it seems to be working as intended? By default, an animated GIF avatar only plays if you hover over it. Whereas if you check "autoplay GIFs" then it should always automatically autoplay. All animated GIFs should be treated exactly the same.

Please provide steps to repro if this doesn't help, but based on my testing it seems this issue can be closed

**Comment by aidalgol** [comment]
Oops.  Sorry, I didn't realise that option applied to avatars as well as GIFs in posts.
