### ISSUE TITLE
Cannot sign in while instance is in whitelist mode

### ISSUE THREAD

**Issue by koyuawsmbrtn** [nolanlawson/pinafore#1795]
Whitelist mode is another feature in Mastodon which allows an instance to cut itself off to just a few instances to prevent abuse. Pinafore doesn't login in this mode. I think this is a bug.

**Comment by aidalgol** [comment]
I get this error message on the Add Instance page when I enter the instance domain and hit "Log in"
> Error: Request failed: 401. Is this a valid Mastodon instance? Is a browser extension blocking the request? Are you in private browsing mode?

**Comment by nolanlawson** [comment]
Thanks for filing the issue. I wonder: is it incumbent upon Mastodon admins to whitelist the clients that they allow as well? Do Halcyon or other web-page clients have this same bug, or just Pinafore?

I'll test this feature out; there may be a way for me to avoid the `/api/v1/instance` API until the user has authenticated.

**Comment by nolanlawson** [comment]
This looks fixed, probably in Mastodon itself (whitelisted the necessary APIs so that they don't require an access token). I can't repro locally with the latest Mastodon release.
