### ISSUE TITLE
Follow request notifications unclear

### ISSUE THREAD

**Issue by aidalgol** [nolanlawson/pinafore#1800]
Pending follow requests show up clearly in the Community tab as a number next to the entry labelled "Follow requests", but under Notifications, they show up for me as two entries for each request, one with the user's display name and one with user's fully-qualified address (e.g. `bob@example.net`), both with the user's profile picture and the five-pointed star icon to the left.  Clicking on either brings me to the user's profile instead of to the follow requests.  (Note, this is with a Pleroma instance; I am unsure whether this behaviour occurs with Mastodon.)

**Comment by nolanlawson** [comment]
I think this must be a Pleroma issue. It sounds like Pleroma treats new follow requests as a notification, and thus they show up in the notifications column? If that's the case, then Pinafore would indeed show each follow request twice, as I am basically working around the fact that Mastodon doesn't provide a notification for this.

Pleroma's behavior sounds very sensible to me, and I think we can detect Pleroma and make its behavior look the same as Mastodon from the perspective of Pinafore.
