### ISSUE TITLE
Pinafore does not run as a PWA on iOS13

### ISSUE THREAD

**Issue by amyspark** [nolanlawson/pinafore#1802]
Hi @nolanlawson ,

I just upgraded my iPad to iOS 13, and my Pinafore home screen links completely stopped working. When I try to open the app, I'm instead redirected to a standard Safari navigation.

I debugged this issue locally, and it turns out Apple now requires a specific meta tag to enable fullscreen PWAs:

```html 
  <meta name="apple-mobile-web-app-capable" content="yes" >
```

**Comment by nolanlawson** [comment]
Pinafore already includes the tag:

```html
<meta content=yes name=mobile-web-app-capable>
```

I'm not sure why this isn't working... maybe it's an iPad-specific issue? I have an iPod Touch running iOS 13, so I will try to get around to testing this soon.

**Comment by nolanlawson** [comment]
Ah I see, the HTML is slightly different - I am missing the `apple-` prefix.
