### ISSUE TITLE
Dockerfile is broken in latest Alpine Linux

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#1826]
Reported here: https://masto.werefox.dev/@shadow8t4/104466855018002782

**Comment by Shadow8t4** [comment]
### TL;DR
Update the Dockerfile to `apk add python3` instead of `python`

**Comment by nolanlawson** [comment]
Seems fixed by https://github.com/nolanlawson/pinafore/pull/1828 unless I missed something
