### ISSUE TITLE
Updates to Dockerfile

### ISSUE THREAD

**Issue by Shadow8t4** [nolanlawson/pinafore#1827]
Referencing #1826 

### Using the [Node Image](https://hub.docker.com/_/node/) instead of pure Alpine

*Issue*: It seems the original contributor opted to have Docker build NodeJS and install Yarn, which is why the image takes such a long time to build. This was likely in order to save on resources originally, as the comments denote.

*Proposal*: If we switch the base image to one that has NodeJS/Yarn installed by default, we can eliminate that build time and not have to worry about unnecessary requirements (the build dependencies needed for this version of the Dockerfile get uninstalled in the build process anyway, so there's no need to install them in the first place if we use an image that already has what we need) If there is a need to slim the image down even more, then we can simply add some command after the yarn build to uninstall yarn and npm maybe.

### Volume mounting instead of `ADD` or `COPY`

*Issue*: `ADD` / `COPY` will take the existing files in the current directory (the repository) and copy them into the docker image's storage. While this is secure, it makes the image by default more bloated than necessary, and causes duplicate storage on the host system's part - since the host will have to store the resources that this repository has, and then also store the containerized copy of those same resources.

*Proposal*: Only copy the necessary dirs for building Pinafore's assets and binaries, then remove them when the build is done. ~~Update the `README` instructions to inform users on Docker's commands to map volumes instead when running the container. Mapping volumes essentially treats the host's copy of the repository as a set of "NAS" drive mounts. This way, we aren't duplicating storage, and we minimize the docker image. This has the added benefit of updating in real time any changes on the repository (i.e. configuration changes, link updates, etc). The `docker-compose.yml` will also need to be updated to handle the proper volume mapping, but `README` changes won't be necessary, end command will be the same if using docker-compose.~~
**Because the static files that are built need to be built during container creation, there is no need to mount volumes. All relevant data for running the service should be stored in the container already, and there are no easy ways of copying that data out onto the host system for volume mapping without having it basically do that at every run time, which could be anywhere from unnecessary to catastrophic when updates happen, and goes against the point of having it in a container.**

I'm testing these changes now, I'll submit a PR once I get them finished. LMK if you have any questions or something to add.

**Comment by nolanlawson** [comment]
Looks fixed in #1828, thanks! These changes all make sense to me. The less we have to maintain ourselves, the better.
