### ISSUE TITLE
If requestIdleCallback is enabled on iOS 13, Pinafore hangs indefinitely

### ISSUE THREAD

**Issue by amyspark** [nolanlawson/pinafore#1833]
In Safari 13, it can be enabled natively as an experimental feature, but if it enabled Pinafore never renders the timeline. If the app is forcibly restarted, the timeline is blank and broken (no profile pic and username) until I go to Settings and reload the PWA; still, toots are never rendered.

Perhaps this line has something to do with it?
https://github.com/nolanlawson/pinafore/blob/00945a3608e5d923462fab8c0a89e1a3d3b2ab46/src/routes/_utils/scheduleIdleTask.js#L11

**Comment by nolanlawson** [comment]
Thanks, I'll test this out!

**Comment by nolanlawson** [comment]
I can repro the issue in iOS 13.6.1. Until the WebKit team ships `requestIdleCallback` as a default (non-experimental) feature, though, I don't think it's Pinafore's responsibility to work around the error. (Also, I have a hard time debugging this on Linux!)

**Comment by nolanlawson** [comment]
The `liteRIC` is not the source of issues, since it only comes into play if `requestIdleCallback` is _undefined_.
