### ISSUE TITLE
Boost/favorite/reply icons invisible in GNOME Web

### ISSUE THREAD

**Issue by aadilayub** [nolanlawson/pinafore#1835]
![pinafore-bug](https://user-images.githubusercontent.com/31581044/88269117-e97f3e80-ccec-11ea-9a04-b92e9c25a4ab.png)

On all posts, the favorite, boost, and reply icons are invisible when using the GNOME Web browser. I tried to inspect and see what the issue was,  but the webpage would crash (this does not happen on other sites).

**Comment by aadilayub** [comment]
Ok, strange, the issue was being caused by using [stevenblack's hosts file](https://github.com/StevenBlack/hosts). Are the icons being loaded from a CDN?

**Comment by nolanlawson** [comment]
Yes, I'm using Vercel's CDN for all assets. Those icons come from `icons.svg` so maybe somehow that was being caught by the adblocker?
