### ISSUE TITLE
placement of "Bookmark toot" in the overflow menu

### ISSUE THREAD

**Issue by abochmann** [nolanlawson/pinafore#1879]
The option for "Bookmark toot" is placed right between two hostile options, "Mute" and "Report". Please consider moving it away from there, maybe below Report or to the end of the menu.

![bookmark option placement](https://user-images.githubusercontent.com/9380844/95692642-87691200-0c27-11eb-9030-bcbb936cd291.PNG)

**Comment by nolanlawson** [comment]
Ah, this is a good catch. Yep, I think it should definitely move.
