### ISSUE TITLE
add a keyboard shortcut to expand cropped media

### ISSUE THREAD

**Issue by iomintz** [nolanlawson/pinafore#1883]
When the user clicks an image, Pinafore displays it full size in a modal. Could we get a keyboard shortcut for that?

**Comment by nolanlawson** [comment]
I've delayed doing this for a while because 1) I couldn't think of the best letter to use, and 2) I'm not sure how to handle multiple images (maybe just always open the first one)?

**Comment by iomintz** [comment]
Open the first one in a gallery that lets you use left/right arrows to navigate. If that would be too much work then just open the first one

**Comment by nolanlawson** [comment]
Makes sense. I'm thinking `i` as the shortcut (`i` for image?) as it's unused.
