### ISSUE TITLE
Bottom of toot appears clickable but isn't

### ISSUE THREAD

**Issue by Krinkle** [nolanlawson/pinafore#1884]
There's an unclickable "deadzone" between buttons where the cursor is turned into a pointer for hover, but no action occurs when clicking.

I found this in context of a follow-only toot (where it additonally causes the disabled button to also appear clickable), but the issue applies to regalar/public toots as well.

![capture](https://user-images.githubusercontent.com/156867/97242735-85d54780-17ec-11eb-8cfe-741626909340.png)

**Comment by nolanlawson** [comment]
I can think of two solutions:

1. don't show a "pointer" hover icon when hovering over the dead zone
2. make it clickable

I tend to prefer #1 because I'm not sure I should allow people to fat-finger... also it would be hard to implement because of the way I'm using flexbox here. But I'm a bit conflicted.

**Comment by nolanlawson** [comment]
A third option is to make the dead zone clickable if the "whole toot" is clickable. This is aesthetically more pleasing in some ways (the whole point is that the entire toot surface area is clickable), although it opens the possibility that people fat-finger on the buttons and open the toot accidentally. Although we already have this problem if they fat-finger any other button, a link, etc., and the feature is optional, so I guess it's okay.

**Comment by Krinkle** [comment]
@nolanlawson Yeah, I think the third option is what I expected it to do.

As I understand it, there's some amount of space around each button still logically part of the button, which I like and makes it easier to use on mobile indeed. Perhaps we can do the same for disabled buttons as well so that continue to capture clicks around themselves to do nothing (for desktop perhaps with a neutral cursor as well). I think it'd be confusing if clicking these disabled buttons would do something unrelated and take the user out of the list they were in.

**Comment by nolanlawson** [comment]
Yeah absolutely. I think disabled buttons should show the hover cursor but just do nothing. It would be weird if clicking them was like clicking the "whole toot."
