### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#19]
I'm not sure we could do this in a privacy-respecting way. I'd really prefer not to handle any user data server-side.

Perhaps it would be possible to extend the Mastodon server API to allow clients to hook into the web push notification system? That way all user data would still reside with the instance, and the web client would just be responsible for receiving pushes.

**Comment by wanderview** [comment]
One way to do this would be to:

1. User opens instance mastodon client and clicks a "prefer pinafore" checkbox.
2. Instance mastodon client sets up push notifications.
3. Notifications include URLs that redirect to pinafore.social

This is basically how I am operating at the moment.  I'm logged into toot.cafe and get pushes from it.  I tend to read and respond in pinafore, though.  The only thing I'm missing is clicking the notification and opening pinafore.

**Comment by nolanlawson** [comment]
Hmmm is there a way we could do this generically, for any web client including Pinafore? I'm thinking:

1. Mastodon adds an [OAuth scope](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#apps) allowing apps to register themselves as notification targets
2. When the user authorizes the app, it's now an option in the main web client
3. (the rest of your flow applies)

The assumption Mastodon would probably have to make is that the app implements the same URL paths as the main web client, e.g. `/statuses/<statusId>`, which I'm currently doing in Pinafore.

**Comment by nolanlawson** [comment]
This is now possible in Mastodon v2.4.0: https://github.com/tootsuite/mastodon/releases/tag/v2.4.0
