### ISSUE TITLE
Emojis broken on instances in secure mode

### ISSUE THREAD

**Issue by IzaliaMae** [nolanlawson/pinafore#1915]
I've tested two different mastodon instances, one in secure mode and the other normal, but the one in secure mode doesn't work. Pinafore spits out a 401 error and doesn't show the picker when clicked. This is on pinafore.social v1.20.0

```
Failed to load resource: the server responded with a status of 401 ()
ajax.js:27 Uncaught (in promise) Error: Request failed: 401
    at ajax.js:27
    at a (ajax.js:48)
    at async f (ajax.js:77)
    at async i (sync.js:18)
    at async u (emoji.js:10)
    at async m (emoji.js:25)
    at async Promise.all (/index 1)
    at async b.onEmojiClick (ComposeToolbar.html:95)
```

**Comment by nolanlawson** [comment]
Based on my reading of [secure mode](https://docs.joinmastodon.org/admin/config/), basically every request needs to be authenticated. This is a bit of a context switch for Pinafore, but it looks like it isn't impossible to fix.
