### ISSUE TITLE
Cursor not placed after person handle when replying to toots

### ISSUE THREAD

**Issue by eli-oat** [nolanlawson/pinafore#1921]
## Environment: 

- macOS 11.1
- Safari 14.0.2

### Expected:
When I select to reply to a toot on Firefox the cursor is automatically placed after the person's handle

### Actual:
When I select to reply to a toot on Safari the cursor is places at the start of the toot, ahead of the person's handle

**Comment by nolanlawson** [comment]
Interesting, thanks for the bug report! I can reproduce on Epiphany Web browser in Linux as well, so it looks like it's WebKit/Safari-specific.

**Comment by nolanlawson** [comment]
No repro in Chrome either, so yep, this is a WebKit bug.
