### ISSUE TITLE
Update Sapper

### ISSUE THREAD

**Issue by Flameborn** [nolanlawson/pinafore#1923]
Currently, Pinafore is using Sapper 0.25.0.

When building on a Raspberry Pi 3, the export server on port *22939* does not start up quick enough, as a result, the build fails due to a timeout.

Sapper has a *--no-timeout* flag to disable this, however, the flag was not respected in 0.25.0. This has been fixed since, see issue https://github.com/sveltejs/sapper/issues/890.

Please update Sapper to a later version where this is fixed, preferably to 0.29.0.

**Comment by nolanlawson** [comment]
I'm on an older Sapper because I'm using Svelte v2. It's not possible right now to update to Svelte v3.

We can hack our fork of Sapper to remove the timeout, though.

**Comment by Flameborn** [comment]
This would allow building, so I think it's a fair compromise. Thank you!

**Comment by nolanlawson** [comment]
Closing in favor of #1924
