### ISSUE TITLE
Arrow keys don't move through poll options

### ISSUE THREAD

**Issue by pitermach** [nolanlawson/pinafore#1928]
Steps to reproduce:

- Using the arrow keys, scroll to a toot that has a poll
- - Tab into the poll options group of radio buttons
- - Attempt to move through the available options by pressing down arrow.

Expected: The focus should move through the available poll options
Actual: The arrow keys still scroll through toots instead.

This problem is a little annoying since the options of a radio button group can't be tabbed between which is the right behavior, but they should then be reachable with arrow keys. I use pinafore with a screen reader in forms mode thanks to pinafore's excellent keyboard support, and right now if I want to interact with a poll I need to go back into browse mode to interact with the poll and then return to focus mode to continue browsing the timeline which takes more keystrokes.

**Comment by nolanlawson** [comment]
Interesting, I must have messed up the accessibility on this somehow. Thanks for opening the issue!
