### ISSUE TITLE
error 500 "undefined is not a constructor" on search in Mobile Safari

### ISSUE THREAD

**Issue by Krinkle** [nolanlawson/pinafore#1938]
Using Pinafore as homescreen web app, Mobile Safari, iOS 13.5.1.

After the latest update/reload, the search page is consistently unavailable:

> **500**
>
> undefined is not a constructor
> (evaluating `new Intl.RelativeTimeFormat(v.a)`)

<img width="200" alt="Screenshot" src="https://user-images.githubusercontent.com/156867/107904399-964c3200-6f43-11eb-8104-633b70d9309b.PNG">

**Comment by Krinkle** [comment]
From [caniuse.com](https://caniuse.com/mdn-javascript_builtins_intl_relativetimeformat), displaying [MDN data](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat#browser_compatibility):

> * IE 11: No
> * Edge 12-18: No; Edge 79+ (since Jan 2020): Yes.
> * Firefox 2-64: No; Firefox 65+ (since Jan 2019): Yes.
> * Chrome 4-70: No; Chrome 71+ (since Dec 2018): Yes.
> * Safari 3-13: No; Safari 14 (since Sep 2020): Yes.
> * iOS 3-13: No; iOS 14 (since Sep 2020): Yes.

**Comment by Krinkle** [comment]
> the search page is consistently unavailable […]

I didn't realize at first, but actually no timelines or other tabs work either (indefinite spinner). The search page stood out as the one page failing with an error message.

**Comment by nolanlawson** [comment]
Looks like I messed up and didn't notice that this is only in iOS 14+. I guess we'll have to include a polyfill.

**Comment by nolanlawson** [comment]
Thanks for letting me know, I was able to repro on my old iPod Touch running iOS 12 (good thing I had it around!). Fix above ^
