### ISSUE TITLE
Additional wellness setting: Absolute timestamps

### ISSUE THREAD

**Issue by kepstin** [nolanlawson/pinafore#2011]
An interesting point that https://medium.com/swlh/user-engagement-is-code-for-addiction-a2f50d36d7ac brings up is that relative timestamps create "immediacy" - you are shown upfront how long ago something was, and can literally see time ticking away, pushing you to interact quickly with fresh content - and it also can encourage folks to wait in real time for new content (fear of missing out).

It seems straightforwards to have a toggle to display timestamps on statuses using absolute timestamps instead of calculating a relative timestamp, especially since the formatted absolute timestamp is already available (shown in the title attribute).

**Comment by nolanlawson** [comment]
It's an interesting idea. It would be nice if there were more research about this – e.g. a peer-reviewed study showing that "x minutes ago" causes more stress than "6:46 pm". Intuitively it makes sense, but of course it would be great to back it up.

That said, even the guidelines I borrowed from the Center for Humane Technology (e.g. grayscale) aren't necessarily super-scientifically-rigorously vetted. I'm pretty sure it's just [hearsay and conjecture](https://www.wired.com/story/grayscale-ios-android-smartphone-addiction/). That said, giving people the option to try it out is not necessarily a bad idea.

And as you said, yes, this should be a fairly easy fix to make in Pinafore.
