### ISSUE TITLE
Disable notification for fav, boost, replies or polls

### ISSUE THREAD

**Issue by mermaidfox** [nolanlawson/pinafore#2087]
Hello,
I have a suggestion to add on the wellness panel.
In mastodon vanilla, you can choose to disable a kind of notification in the column. It can be for fav, boost, replies, polls, new follower, ...
![Capture d’écran du 2021-08-10 15-47-25](https://user-images.githubusercontent.com/10085354/128878475-8db9bd07-5a18-499e-8499-b42a687ed7e3.png)
The same is available in mastodon glitch-soc
![Capture d’écran du 2021-08-10 15-49-05](https://user-images.githubusercontent.com/10085354/128878720-2fdbc84a-e800-4e48-b6f8-c32acf186077.png)

Can we have something similar on Pinafore ?
In my case, I want to not be distracted by favs, and focus in interacting with people.

Thanks Nolan

**Comment by nolanlawson** [comment]
These options are in the individual instance options. E.g. Settings -> Instances -> (Instance name). I put it there because it's possible to configure this separately for each instance, not just globally.

Hope that helps! Let me know if that works for you.
