### ISSUE TITLE
accounts instead of Instances would be great.

### ISSUE THREAD

**Issue by dhuschde** [nolanlawson/pinafore#2092]
Hey,
I have the problem that I have multiple Accounts on one Instance and want to add all of them to pinafore.
But I can only add one per Instance.

Is it possible to change that?

**Comment by ScootRay** [comment]
I was wondering how to do the same since I have the same issue. I have more than one account on the same instance so folks can follow different blogs I host.

Thanks!
Ray

**Comment by nolanlawson** [comment]
This is a duplicate of #39.

TBH it's unlikely that I will get around to implementing it and it would be a massive rewrite of much of Pinafore's core storage and routing logic. In the meantime I would recommend using `pinafore.social` for one account and `dev.pinafore.social` in another tab for the other account. Sorry about that.
