### ISSUE TITLE
Status bar color broken after visiting a link in iOS PWA

### ISSUE THREAD

**Issue by hellojaccc** [nolanlawson/pinafore#2104]
![image](https://user-images.githubusercontent.com/71537512/150478119-d60ebcc5-1713-43e0-a87d-06c97ef4ed25.png)

![image](https://user-images.githubusercontent.com/71537512/150478156-759e5afc-d4e7-408c-b542-0bae8f4fee71.png)

How to reproduce : open any external link, and close by swiping left to right. (not clicking done button)

Status bar will have external website's color, instead of blue

This does not occur in for example, libreddit

**Comment by hellojaccc** [comment]
<meta name="apple-mobile-web-app-status-bar-style" content="white" >
- pinafore

<meta name="apple-mobile-web-app-status-bar-style" content="default">
- libreddit

![image](https://user-images.githubusercontent.com/71537512/150480968-124bc302-51b7-40e0-b799-fc8f8be7dd1a.png)

As you can see from the screenshot, libreddit also has transparent status bar

**Comment by nolanlawson** [comment]
Hm so I guess I should switch to `content="default"`. This thing is non-standard and I haven't tested it in every iPhone model, so it doesn't surprise me that it's broken.

**Comment by nolanlawson** [comment]
This really kind of seems like an Apple bug.
