### ISSUE TITLE
Uploading 2MB video results in 500 Internal Server Error

### ISSUE THREAD

**Issue by Krinkle** [nolanlawson/pinafore#2120]
I tried several times in a row and getting the same error.

Doing the same through the Mastodon interface works without error. I imagine its using a different API?

<img width="1066" alt="Screenshot 2022-04-09 at 22 06 07" src="https://user-images.githubusercontent.com/156867/162591711-dc8b4adb-e6cf-4c4c-914f-f7accf17be60.png">

**Comment by nolanlawson** [comment]
Yeah I'm guessing that I need to use the v2 media API: https://github.com/nolanlawson/pinafore/issues/2078

**Comment by nolanlawson** [comment]
Should be fixed in https://github.com/nolanlawson/pinafore/pull/2121, will be released to dev.pinafore.social soon and production a bit after that. Thanks!
