### ISSUE TITLE
Any plan for migrating to Svelte 3?

### ISSUE THREAD

**Issue by Shaokun-X** [nolanlawson/pinafore#2139]
Hello! This is really a cool project, thanks for all your work!

I see that it is basically written in Svelte 2, but the Svelte team seems to have given up the version 2, even the development of [upgrading tool](https://github.com/sveltejs/svelte-upgrade) has been stopped for years. I know it would be a lot of work but I am still wondering is there any plan to migrate to Svelte 3?

**Comment by nolanlawson** [comment]
No, no plans for that. I consider Pinafore in "maintenance mode," in that I don't plan any big rewrites or anything. I occasionally add little bits and pieces here and there, but rewriting it all in Svelte 3 would be a huge migration with very little payoff. (It's not clear to me that anything really improved between Svelte 2 and 3 besides a nicer authoring syntax and better integration with stuff like SvelteKit.)

There is a fork of Pinafore somewhere that someone wrote that migrated it to Svelte 3, but I forget what it's called and I dunno if it was open-sourced.
