### ISSUE TITLE
Tag search consistently missing most relevant result

### ISSUE THREAD

**Issue by Krinkle** [nolanlawson/pinafore#2158]
The following examples are when logged-in from https://mastodon.technology/, but I imagine similar results can be found from other instances.

Search for "algorithm":

<img height="305" alt="Screenshot" src="https://user-images.githubusercontent.com/156867/192867489-751fa533-f4ca-408d-a988-faf38beb1e99.png">

What I'm most interested in is `#algorithm` and posts I bookmarked/starred/authored/etc that mention the word. There appears to be no way in the interface to get to `#algorithm`. Even searching for it explicitlty:

<img height="305" alt="Screenshot" src="https://user-images.githubusercontent.com/156867/192867443-a3c0eed7-f803-41da-a4e2-9808d7ca8054.png">

Workaround: Click one of the other results and change the URL.

Another result I'd be interested in is `#algorithms`, as sometimes the plural is more commonly used. Similarly, no way to get there.
<img height="387" alt="Screenshot" src="https://user-images.githubusercontent.com/156867/192868161-7a03a21b-3474-40a8-9449-31cc46643e5d.png">

I note that the alternate tags shown in the results, each of when when clicked, yields "Nothing to show.", suggesting there are no matching posts anymore in the index with this tag, not a single one.

I'm fairly certain there's at least something to this that's to blame on the Mastodon API backend and not Pinafore, but in the first party web UI I've not encountered this issue. At least the verbatim result named after my search appears there for me most times.

**Comment by nolanlawson** [comment]
I need to check the API usage of the Masto frontend vs the Pinafore frontend to see what they're doing differently. They're always changing things around in the API.

**Comment by Krinkle** [comment]
Appears to be fixed in Semaphore. Not sure if due to fix pre-fork, or perhaps due to a fix in Mastodon API. Either way LGTM.
