### ISSUE TITLE
[Accessibility] Feedback from screen reader user: two <h1> at certain times

### ISSUE THREAD

**Issue by fasiha** [nolanlawson/pinafore#2162]
On [Twitter](https://twitter.com/sasha_chudesnov/status/1586880679245221894), Sasha Chu praises Pinafore and offers a bug report:

> Just tried it out. Pretty great, especially the quality of UX writing (labels on icon elements). The only issue is that there are two level 1 headings on the page when both the toot compose tool and the list of your posted toots are visible at the same time.

**Comment by nolanlawson** [comment]
Ah, this is news to me. I know that there was only supposed to be one `<main>` at a time, but I didn't know that multiple `<h1>`s on the same page were a problem. Looks like an oversight on my part.

I guess the solution is to use `<h2>`s instead? And there could be a screenreader-only `<h1>` above the two.
