### ISSUE TITLE
Accessibility: Add an aria-live region for keyboard shortcuts

### ISSUE THREAD

**Issue by TheQuinbox** [nolanlawson/pinafore#2163]
It would be awesome if we could get speech feedback when favoriting, boosting etc. For example, right now, if I press B to boost, I don't hear anything. I have to manually check if it worked. The main solution I can think of is to add an aria-live region to report this information.

**Comment by nolanlawson** [comment]
This seems doable, yes. I think this would only apply to keyboard shortcuts, since you get feedback when pressing the button.
