### ISSUE TITLE
malformed notification causes notifications page to load forever

### ISSUE THREAD

**Issue by codl** [nolanlawson/pinafore#217]
```
Uncaught (in promise) TypeError: Cannot read property 'reblog' of null
    at ie._recompute (Status.html:168)
    at new ie (Status.html:141)
    at r (Notification.html:4)
    at Notification.html:1
    at new u (Notification.html:1)
    at new f (NotificationVirtualListItem.html:7)
    at VirtualListItem.html:9
    at new y (VirtualListItem.html:5)
    at F (VirtualListLazyItem.html:6)
    at Object.p (VirtualListLazyItem.html:1)
```

digging through network requests reveals that one of the notifications coming from mastodon has a null `status`

![2018-04-23t11-07-33-0o0o](https://user-images.githubusercontent.com/315139/39117192-b50f2f7c-46e6-11e8-82f6-a270cea66506.png)

I'm not sure what causes this but it'd be better to handle it cleanly

**Comment by nolanlawson** [comment]
That's odd; you can't favorite "no status"… but yeah we should be resilient to malformed notifications.

Which Masto server is doing this, and which version? Methinks we should file a bug on Mastodon itself. Maybe it does this when the status gets deleted? (Race condition?)

**Comment by codl** [comment]
yeah i did file a bug with mastodon as well https://github.com/tootsuite/mastodon/issues/7240

**Comment by codl** [comment]
the gist of it was "it's a race condition, it happens, and theres been an issue open for it for two years"
