### ISSUE TITLE
Theme with both light / dark variant at the same

### ISSUE THREAD

**Issue by iamdtms** [nolanlawson/pinafore#2212]
https://web.dev/prefers-color-scheme/
https://iamdtms.github.io/theme-switcher-template/
https://iamdtms.github.io/theme-switcher-template/assets/script/site.js

at **https://pinafore.social/statuses/109372245747053441**

**Comment by nolanlawson** [comment]
This looks like a duplicate of https://github.com/nolanlawson/pinafore/issues/2141

BTW you cannot share status URLs directly from Pinafore – you have to click the three dots, then "copy link to toot." (Incidentally, the main Mastodon frontend has the same issue. :slightly_smiling_face: )

Closing as a duplicate! Thanks for opening.
