### ISSUE TITLE
Navigation bar location stuck at bottom in Firefox w/DarkReader

### ISSUE THREAD

**Issue by wlonkly** [nolanlawson/pinafore#2216]
This is a weird edge case and I can work around it easily, but I thought I might as well let you know:

In Firefox with the DarkReader extension enabled in Dynamic mode, the "Place the navigation bar at the bottom of the screen" has no effect -- the navigation bar shows at the bottom regardless of its setting.

I couldn't quite narrow down what CSS magic is tripping it up, and of course I've disabled DarkReader on pinafore.social to fix it. But in case someone else runs into the same problem, now you know!

(I don't have DarkReader installed in Chrome to test with, but I wouldn't be surprised if the same problem occurs.)

**Comment by nolanlawson** [comment]
Extensions can add whatever JS/CSS they want to a page; it definitely has the potential to mess things up! Not sure how this happened, but maybe they are using CSS custom property names that conflict with Pinafore's.

**Comment by wlonkly** [comment]
Understood, and I definitely don't expect you to _fix_ this based on just my report, but I wanted to make sure you knew about the interaction in case other reports come in!

**Comment by wlonkly** [comment]
Closing to tidy up my open issues list now that Pinafore is no longer being maintained.
