### ISSUE TITLE
"Loading more" alert creates extraneous verbosity for screen reader users

### ISSUE THREAD

**Issue by jcsteh** [nolanlawson/pinafore#2226]
Thanks for such a fantastic, delightful Mastodon client.

Strictly speaking, the "Loading more" alert is correct a11y because it makes it clear that more content is loading, which would otherwise not be obvious. On the other hand, pragmatically speaking, I find this very distracting and intrusive as a screen reader user, as it interrupts my browsing of the timeline. I can silence it of course, but it is still jarring.

I think it would be worth considering removing this alert, though this would obviously need feedback from other screen reader users.

CC @MarcoZehe for his thoughts as another screen reader user.

**Comment by nolanlawson** [comment]
@jcsteh Hmmm interesting, this wasn't specifically something I added only for screen reader users – the footer transforms into a spinner alongside the explicit visible test "Loading more." However, I imagine that 99% of the time, this text flashes for a brief moment before the network request returns. So from a screen reader's perspective it probably announces the text every time. (And for sighted users, there is an opacity animation from 0 to 1, so it's less jarring.)

I think I could fix this by adding a delay to when the `aria-hidden="false"` is set. For instance, it could wait 1 second before doing so. Or I could explicitly make it a live region with `aria-live="polite"`. My hunch is that the first one is better, but which one would you prefer?

**Comment by MarcoZehe** [comment]
Does this one have a role="alert"? If so, that has an implicit aria-live="assertive" attached to it. This is what makes it jarring. If you removed the role attribute and set aria-live="polite" instead, it would still announce when loading new stuff or some similar, but be non-intrusive. Much like the "Favorited" and "Boosted" announcements you made talk recently.

**Comment by jcsteh** [comment]
It does have role="alert". My gut feeling is that this should just be removed. The downside is that screen reader users wouldn't get notified that content is loading. However, given how quick this usually is, I'm not sure how useful this is. By the time the announcement has occurred, the content has probably finished loading.

aria-live="polite" might be better than role="alert", but this might still mean that the announcement occurs before the text of the newly focused item.

If the concern is that screen reader users wouldn't know about slow loads, another option is to not have role="alert" by default, but set role="alert" if the message is displayed for longer than, say, 1 second. This way, a screen reader user wouldn't get the message in most cases, but they'd know about it within a second if the load was taking too long. This obviously isn't equivalent to the sighted UX, but I think it's more pragmatic.

**Comment by MarcoZehe** [comment]
I think this would be a good compromise.

**Comment by jcsteh** [comment]
I'm curious, @MarcoZehe: do you find the "Loading more" message useful? I guess I figure that if I hit down arrow and I get nothing, there's probably nothing more to get right now. The only reason I ask is that implementing the 1 second delay behaviour feels to me like a very complicated, potentially brittle hack for a pretty rare use case. Just trying to balance purism with pragmatism here.

**Comment by MarcoZehe** [comment]
@jcsteh no, not really. Because the message is spoken once the last or second to last toot is being hit that is currently available, so that by the time you actually get to the point where new toots start, the loading has definitely already finished. So yeah, I'd be fine with just removing the role and have this particular message just shut off.

**Comment by nolanlawson** [comment]
I'm not familiar with the subtleties of how different screen readers / UAs handle this kind of UI, so I appreciate the context here! I'm happy with just removing the `role=alert` if you both prefer that.

Adding an `aria-live=polite` after 1 second also feels like a "nice to have" (a bit brittle, to be sure), but I'm not sure it's even worth the effort if we remove `role=alert`?

**Comment by MarcoZehe** [comment]
Yeah, that's why I decided to take the pragmatic approach earlier today and provided a PR to just remove that alert.
