### ISSUE TITLE
"favorite" star icons across almost all themes are difficult to distinguish

### ISSUE THREAD

**Issue by asadotzler** [nolanlawson/pinafore#2230]
The favorite control, a star icon that has two states, on and off, is difficult to distinguish for all but the Cobalt theme. Even if I could distinguish them, for most of the themes it's unclear which is the "on" and which is the "off" state. Testing on Version 2.3.2 in latest Firefox with nearly every theme available in Pinafore's Settings. The Cobalt theme does it right, by making the color change not just a change in brightness, but a change in hue. Even better would be a change in shape too (filled vs unfilled would count) as using color alone is problematic for many people with atypical vision, like color blindness.

**Comment by NickColley** [comment]
I'm going to try and resolve this soon!

**Comment by nolanlawson** [comment]
Thank you for reporting. There are quite a few bugs about this, which I've organized by adding the `contrast` tag ^

**Comment by NickColley** [comment]
We have resolved being able to distinguish between on and off with https://github.com/nolanlawson/pinafore/pull/2234

Once we improve the overall contrast this'll resolve the remaining issues around icons being difficult to see.

**Comment by asadotzler** [comment]
Nick, thank you for your quick reply and for taking action (and what I think is the most correct action, shape change and not just color change.) As I'm sure you know, A11Y efforts often go un- or under- appreciated and I want to make absolutely sure that's not the case here. Thank you. Thank you also to Nolan for the assist. I will also post a follow up to my "toot" (gosh do I dislike that label) that inspired this bug report thanking you (and nolan) for making this improvement once it's live. (I've tested it on the preview server but don't want anyone reading my update to go looking on the live server and thinking it isn't working, so I'll wait a bit.)

**Comment by NickColley** [comment]
We've merged a bunch of improvements so I think we've resolved this but if you find any places that are still hard to read feel free re-open and I'll address it.
