### ISSUE TITLE
Proposal for review: Include 'check' icon for boosts and favourites

### ISSUE THREAD

**Issue by NickColley** [nolanlawson/pinafore#2231]
Continuation of https://github.com/nolanlawson/pinafore/pull/2210

While I'd like to at some point do something more elegant but for now I think aligning with the main mastodon's approach of having check icons might work nicely to achieve a clear shape difference without relying on colour. 

It does so without increasing the status toolbar's place in the visual hierarchy ensuring the toot itself is not dominated by the active button.

<img width="214" alt="Screenshot 2022-11-23 at 12 38 33 pm" src="https://user-images.githubusercontent.com/2445413/203548938-616e1969-74f0-457f-b998-49b856a6ec4f.png">

Benefit of this approach is we can make the regular buttons a more neutral grey (or keep as is) which I think aligns with your vision @nolanlawson let me know if you like this and I'll work on it.

<img width="632" alt="Screenshot 2022-11-23 at 12 44 24 pm" src="https://user-images.githubusercontent.com/2445413/203550055-c4365202-467c-48b8-b1fb-1f9b85045829.png">

p.s. @nolanlawson would you mind making me a contributor so I can add labels and do house keeping of access issues etc?

**Comment by NickColley** [comment]
Would resolve https://github.com/nolanlawson/pinafore/issues/2215 https://github.com/nolanlawson/pinafore/issues/2230 and some of https://github.com/nolanlawson/pinafore/issues/2159

**Comment by NickColley** [comment]
In the future I'd like to explore having an icon set where we have outlined and then filled in icons but that would be a lot more work and I think we should fix this ASAP and get the client to a good baseline before being more ambitious.

**Comment by neuhaus** [comment]
I agree this is a good solution if the long term solution is to go from outlined to filled icon 👍

**Comment by NickColley** [comment]
Nice, let's add the check then, we'll need to do a pass of colour changes for general contrast regardless but that can be separate.

Will work on a pull request...

**Comment by nolanlawson** [comment]
@NickColley I've made you a collaborator. `master` branch is `dev.pinafore.social`, `production` is `pinafore.social` – ping me and I can do a release to production. So now you know how it works. :slightly_smiling_face:

**Comment by NickColley** [comment]
https://github.com/nolanlawson/pinafore/pull/2234
