### ISSUE TITLE
Error with yarn run dev

### ISSUE THREAD

**Issue by nvdaes** [nolanlawson/pinafore#2270]
I get the following error:
                                                                                                                         
./webpack/webpack.config.js → ./webpack/webpack.config.cjs...                                                           
ERROR: "build-assets" exited with 1.                                                                                    
error Command failed with exit code 1.                                                                                  
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                    
ERROR: "before-build" exited with 1.                                                                                    
error Command failed with exit code 1.                                                                                  
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.                                    
 
## Environment

* Windows Version 10.0.22621 compilación 22621
* Node v18.12.1
* Yarn 1.22.19

Thanks.

**Comment by nolanlawson** [comment]
Sorry, this is not enough information to debug. Pinafore's build is somewhat OS-dependant, so you may have to debug to figure out what about your environment is causing it to fail. E.g. I use Node v14 but you're using Node v18.

If I had to guess, I'd say it's because you're using Windows. I never made an effort to ensure that Pinafore would build on Windows. You might try Windows Subsystem for Linux to see if that works.

**Comment by nvdaes** [comment]
Thanks for your reply and advice! It works using Windows Subsystem for Linux with Node v18.
You may want to update the documentation.
For reference, in case it helps Windows users, I used this resources to prepare my  environment:

- [Set up Node on WSL](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
- [Installing Yarn on WSL](https://dev.to/bonstine/installing-yarn-on-wsl-38p2)

**Comment by nolanlawson** [comment]
Thanks!
