### ISSUE TITLE
Support toot edited notification

### ISSUE THREAD

**Issue by graue** [nolanlawson/pinafore#2280]
When a toot is edited on a newer Mastodon or Pleroma server, everyone who boosted that toot gets a notification.

In Pinafore, currently, this notification shows up as just the toot, with no context for why it's showing up as a notification:

![notif](https://user-images.githubusercontent.com/1730853/204695787-e9275b02-a3de-4934-9337-ce664d7f5ddf.jpg)

The equivalent notification on Mastodon 4.0.2 web is labeled, "[person's name] edited a post":

![notif2](https://user-images.githubusercontent.com/1730853/204696030-a31c9b8e-7403-4cbf-ad07-a1286a5153fb.jpg)

(Hope this visual still makes sense with pixelization; I'm trying to preserve the tooter's privacy.)

Not sure if you want to group this with the related issue for supporting editing, #2179. IMO it would be valuable to have this notification make sense even without Pinafore supporting editing one's own toots. (Maybe there should be a third issue for viewing past versions of edited toots?)

**Comment by nolanlawson** [comment]
Oof that's a nasty bug. Yeah it's probably because Pinafore doesn't know what to do with the notification type.
