### ISSUE TITLE
Pull request for Digest tab?

### ISSUE THREAD

**Issue by samuk** [nolanlawson/pinafore#2304]
If someone was to write some  'digest' code along these lines: 

https://wiki.jon-e.net/Masto_Forks/DIY_Algorithms
https://github.com/hodgesmr/mastodon_digest

Would you in principle be interested in using that code in Pinafore as an optional timeline? Or are you in principle against that sort of thing?

**Comment by nolanlawson** [comment]
@samuk I don't quite understand what this is, but assuming you're talking about having Pinafore connect to something other than the Mastodon instance the user is signed in to (i.e. a custom timeline server) then yes, I would be opposed to that.

OTOH if it's an ActivityPub server that can speak the Mastodon dialect of server-client communication then sure, Pinafore can connect to it, no problem. Although modifying Pinafore's UI to detect that the server supports this other kind of timeline and then displaying it would probably be non-trivial work. :slightly_smiling_face:

**Comment by samuk** [comment]
Thanks
