### ISSUE TITLE
Allow a faster method to close full-sized images

### ISSUE THREAD

**Issue by jet082** [nolanlawson/pinafore#2320]
This is a bit of a strange request, but I feel like on most websites, when you click an image to view it full-size, you can click it again to close it. Or, if not that, clicking outside of the full-size image will close it. In Pinafore, currently, one must move the mouse over to the X and select that to close the image. This is, to my mind anyway, non-standard behavior and a lot of mouse movement that could be reduced.

Currently, I've taken to tabbing over to the X and pressing space to close the image instead of using the mouse, but it would be nice to reduce the interaction to a simple 'click to open, click to close, left/right-keyboard-key to alternate between images in a gallery (or mouse click on the arrow at the bottom of the image)'

**Comment by nolanlawson** [comment]
Thanks for the request. You can use the Esc key to close an image. Or the browser back button. Or you can click outside of the image. Sometimes you have to click very far outside the image if it is a large image that fills up most of the screen. Hope that helps!
