### ISSUE TITLE
Opening and closing tooltips is not communicated to assistive technologies

### ISSUE THREAD

**Issue by nvdaes** [nolanlawson/pinafore#2321]
When we press tooltip buttons, text can be shown and hidden, but this is not notified to screen readers. Though a description is read in certain cases without needing to expand the button (for example, using single character navigation with NVDA), we can press the button and then the webpage is modified, so it's useful to know that the button is expandable.
I've tested this locally and for me is clearer to be notified about this with NVDA screen reader.

**Comment by NickColley** [comment]
Merged in #2322 thank you :)
