### ISSUE TITLE
Favourite instance icon

### ISSUE THREAD

**Issue by Fastidious** [nolanlawson/pinafore#2330]
Go to Settings → General → Theme → Pitch Black. Then Settings → Instances. The favourite icon is pretty much invisible.

**Comment by NickColley** [comment]
I think will be fixed with: https://github.com/nolanlawson/pinafore/pull/2328

Thank you for reporting as always, appreciated.

**Comment by NickColley** [comment]
We've merged a bunch of improvements so I think we've resolved this but if you find any places that are still hard to read feel free re-open and I'll address it.
