### ISSUE TITLE
dark color schemes have a white bottom in Firefox

### ISSUE THREAD

**Issue by Oreolek** [nolanlawson/pinafore#2341]
i reset the browser cache and logged in again to check

Dark scheme:
![1](https://user-images.githubusercontent.com/308627/210220124-e52d7d44-ad3a-4c93-a663-6c7417faa3ab.png)

Light scheme:
![2](https://user-images.githubusercontent.com/308627/210220126-33f8c3a2-8736-4c08-9780-bc3993bdd027.png)

Firefox 108.0

**Comment by Nikurasukun** [comment]
I can't reproduce it in my instance of pinafore 2.6.0
https://pina.cat-enby.club
Is this fixed or does it still happen to you?
Which version and instance have you used when this happens?

**Comment by Oreolek** [comment]
Apparently this is a Firefox bug and it can pop up on Windows and any website. No fix for now.
