### ISSUE TITLE
Make clear when a post is part of a thread

### ISSUE THREAD

**Issue by mirabilos** [nolanlawson/pinafore#2345]
https://pony.social/@thephd/109625881926371334 in the home timeline was not clearly visible as thread to me (it’s a self-reply, so no `@someone` in the beginning; no other visual indication).

This could be better, ideally by marking all posts that are a nōn-first post of a thread somehow (and consistently).

**Comment by nolanlawson** [comment]
Thanks for opening this issue! This appears to be a duplicate of https://github.com/nolanlawson/pinafore/issues/2214
