### ISSUE TITLE
Fork of Pinafore with many curation features

### ISSUE THREAD

**Issue by mitotic** [nolanlawson/pinafore#2346]
Just letting you know that I added a bunch of curation features to a fork of Pinafore. You can find it at https://github.com/mitotic/pinafore-mahoot

As a recent migrant to Mastodon from the other microblogging site, I developed it primarily to give me more control over how I consume social media. Pinafore turned out to be an ideal platform to do this because it is a stand-alone web client.

I don't fully understand how Pinafore works. Therefore, the code is very "hacky". The goal is not to create a polished product but to demonstrate what's possible with purely client-side curation. If there's interest, some features could be merged into Pinafore in the future. (There are a couple of small fixes I made, related to paged fetching of follow lists and display of the profile image, that I could submit to be pulled into Pinafore now.)

Comments and suggestions are welcome (and thanks for creating Pinafore)!

**Comment by nolanlawson** [comment]
That's cool! Thanks for letting me know. :)

TBQH I don't have the energy to maintain Pinafore anymore. I would prefer at this point to put it in "maintenance mode" and not accept any new features. I think it would be great to keep Pinafore as a example of a fediverse client that others can fork and learn from, as you have.

I would encourage you to fork Pinafore and host it with your improvements! It would be great to have different fediverse clients customized however people want. :)
