### ISSUE TITLE
Hitting ctrl+enter when cursor is in compose textarea should post toot

### ISSUE THREAD

**Issue by blackle** [nolanlawson/pinafore#24]
On mastodon.social (and twitter) pressing ctrl+enter when typing a toot will send that toot.

**Comment by rowanlupton** [comment]
yeah, cmd+enter on macs. also on github, fwiw ;)

**Comment by selfagency** [comment]
keyboard shortcuts overall should happen— n for new toot, r for retoot, etc.

**Comment by ruthtillman** [comment]
re ^^ Keyboard shortcuts on the whole are nice, but I appreciate the scope of this ticket because as I've been learning in 2 days of using Pinafore, it's very much muscle memory when posting! 😅
