### ISSUE TITLE
iOS pre-11.3 doesn't recognize Pinafore as a PWA

### ISSUE THREAD

**Issue by noiob** [nolanlawson/pinafore#248]
On anything before iOS 11.3 which add support for the manifest.json, Pinafore displays browser chrome, even though `<meta name='apple-mobile-web-app-capable' content='yes'>` is set. Sites like mastodon.social exhibit the correct behavior.

**Comment by nolanlawson** [comment]
Interesting, it looks like `mastodon.social` uses:

```html
<meta content='yes' name='apple-mobile-web-app-capable'>
<link href='/apple-touch-icon.png' rel='apple-touch-icon' sizes='180x180'>
```

whereas Pinafore uses:

```html
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120.png" >
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180.png" >
  <meta name="mobile-web-app-capable" content="yes" >
  <meta name="apple-mobile-web-app-title" content="Pinafore" >
  <meta name="apple-mobile-web-app-status-bar-style" content="white" >
```

Perhaps I need to remove some of these to make iOS <11.3 behave?

**Comment by spriteclad** [comment]
I think you just need to add `<meta content='yes' name='apple-mobile-web-app-capable'>` to the <HEAD> and that might make it work with older versions? I'm not entirely sure, though.

**Comment by noiob** [comment]
it has `<meta name='apple-mobile-web-app-capable' content='yes'>`, does the order really matter?

**Comment by spriteclad** [comment]
Not really, I'm assuming it should work either way?

**Comment by nolanlawson** [comment]
Pinafore is currently disabling PWA support on iOS due to #45, we will revisit once Safari fixes that particular bug
