### ISSUE TITLE
Option for alternative UI for images/media

### ISSUE THREAD

**Issue by jelv** [nolanlawson/pinafore#258]
Currently all images are displayed below each other. A improvement would be to use the Halcyon grouping. Halcyon groups thumbnails in nice small group. The good points:

- Max height around 500px, even with multiple images
- [Focal point](https://medium.com/tootsuite/the-mastodon-spring-creators-release-65f60d0edb8c) used for thumbnails

Halcyon:
![screenshot_1](https://user-images.githubusercontent.com/7106279/39563530-e11215b8-4eb0-11e8-86cf-3037d4ec210c.png)

Pinafore:
![screenshot_2](https://user-images.githubusercontent.com/7106279/39563531-e12eae4e-4eb0-11e8-8f6f-d69bd041d2df.png)

**Comment by nolanlawson** [comment]
Related work from @sgenoud https://github.com/nolanlawson/pinafore/commit/9105657920ca772d95083322c00e05a353411f11
