### ISSUE TITLE
Viewing threads doesn't work in Pleroma because of wrong request

### ISSUE THREAD

**Issue by lambadalambda** [nolanlawson/pinafore#26]
I tested Pinafore with Pleroma, it works very well, except for viewing threads / posts. The browser does a request with an added `}` to the path, example: `https://pleroma.soykaf.com/api/v1/statuses/7812305}`.

Otherwise, it looks and works very well!

**Comment by nolanlawson** [comment]
Oops, that's a dumb bug on my part. I'll fix it.

**Comment by nolanlawson** [comment]
Should be fixed in v0.1.1, deployed now. Check https://pinafore.social/settings/about to see which version you're running. :)
