### ISSUE TITLE
Export as static site

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#27]
This is useful for folks who want to self-host Pinafore but don't want to spin up a whole Node server to do so. It'd also be useful for hybrid mobile apps.

In theory `sapper export` should work, but I'm on an older version of Sapper and so it doesn't. Need to either 1) upgrade Sapper, or 2) write my own script to crawl the various URLs and generate a static site. (2) may be easier given all the modifications I've made to the Sapper code.

**Comment by chr-1x** [comment]
you're probably pretty busy with higher priority stuff but i'd just like to throw in my support for this; i'd love to deploy it on cybre.space but i want it to be as light of an addition to the server as possible

**Comment by nolanlawson** [comment]
Two issues it'd be hard to solve as a static site:

1. Dynamic URLs like `/tags/<myhashtag>` or `/settings/instances/<myinstance>` would not work when you refresh unless the Service Worker is activated, it's not a cold cache load, and it's not a hard-refresh. Probably a minor bug though.
2. More worryingly, CSP would have to be managed by the admin. Probably we could just provide an nginx/Apache snippet for folks to add, but CSP is important since we're injecting raw HTML into the DOM from instances (although your own instance would have to be malicious... but still).

**Comment by nolanlawson** [comment]
This is probably blocked by #416 because latest Sapper has export built-in.

**Comment by nolanlawson** [comment]
fixed by https://github.com/nolanlawson/pinafore/pull/775, there is now `npm run export`
