### ISSUE TITLE
The notification badge should be in a different color.

### ISSUE THREAD

**Issue by shellkr** [nolanlawson/pinafore#277]
Right now it can be difficult to discover if you have gotten a notification. I think either change the badge or the bell (to red?) could work.

**Comment by nolanlawson** [comment]
One of my goals with Pinafore is to make notifications a little less jarring, a little less urgent... this is why I don't have a "boop" sound, for instance. I was even on the fence about the red dot in the favicon. We do now have an unread count in the page tab title, though. I'm inclined to keep it as is, but thanks for the feedback!
