### ISSUE TITLE
20 second timeout may be too aggressive

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#29]
The goal is to fallback to offline mode when offline, but for some instances this means media uploads just don't work. Upping to 30 seconds or having a higher timeout for media would be a potential fix.

**Comment by Lucidiot** [comment]
I am currently using Mastodon on an horrible connection and I would need at least a minute of timeout. Maybe show a 'Abort' or 'Offline mode' link when the loading gets too long?
