### ISSUE TITLE
Support for private browsing (Safari, Edge, Firefox)

### ISSUE THREAD

**Issue by jumoru** [nolanlawson/pinafore#30]
When using Safaris private mode it shows an error page saying that it can't open the site after entering the 2FA code for your instance. All extensions were disabled.

Safari 11.1 on macOS 10.13.4

Screenshot (in German):
![bildschirmfoto 2018-04-09 um 18 28 46](https://user-images.githubusercontent.com/27491477/38511195-a91d389a-3c27-11e8-824e-6b8dec727c89.png)

**Comment by nolanlawson** [comment]
Yes, it's also broken in Firefox and Edge private mode (not sure about Chrome). This is due to heavy reliance on LocalStorage and IndexedDB, which has wonky support in private browsing mode.

**Comment by jumoru** [comment]
For me it works in Chrome.

**Comment by nolanlawson** [comment]
I did the best I could to provide functionality in private browsing mode. Unfortunately it varies from browser to browser, but #733 is about as good as I can do without including a full IndexedDB polyfill.
