### ISSUE TITLE
Can't add an instance if there's a trailing slash in the URL

### ISSUE THREAD

**Issue by timmc** [nolanlawson/pinafore#31]
I tried to add `https://i.write.codethat.sucks/` as an instance and received this error:

`Error: NetworkError when attempting to fetch resource.. Is this a valid Mastodon instance?`

Nothing stands out in the dev console or network log (and I don't see a request attempt being made.)

Firefox ESR 52, Debian Linux 9. Is this maybe an issue with Service Workers? I see that entered Firefox in January 2018.

**Comment by notlmn** [comment]
Just remove the trailing slash and it works, just a bug while concatenating url string.

**Comment by mlcdf** [comment]
If you use Privacy Badger, try disabling it.

https://toot.cafe/@nolan/99830411140429778

**Comment by timmc** [comment]
Different error after correcting that, or using an empty browser profile: `Error: undefined. Is this a valid Mastodon instance?` I see an OPTIONS, a GET, and a POST, all succeeding. In the console, an `InvalidStateError` and then some error event involving the string `IDBOpenDBRequest`. Something to do with IndexedDB?

**Comment by timmc** [comment]
Self-closing as dupe of https://github.com/nolanlawson/pinafore/issues/23

**Comment by nolanlawson** [comment]
I just tested and indeed it doesn't seem to work if you add a trailing slash (with or without Privacy Badger). Re-opened.
