### ISSUE TITLE
Unable to login from Tor Browser

### ISSUE THREAD

**Issue by KellerFuchs** [nolanlawson/pinafore#312]
I attempted to use my account on vulpine.club, using Tor Browser (version 8.0a7, which is based on Firefox ESR 52.8.0), which I use for the “regular” Mastodon UI, and simply couldn't login, displaying “Error: undefined”.

Here is a screenshot of the browser window, showing the error message and the messages from the Javascript console:
![screenshot-pinafore](https://user-images.githubusercontent.com/14331571/40318397-02c204fe-5d14-11e8-9ec4-e2630dcc999b.png)

**Comment by nolanlawson** [comment]
Thanks for reporting the bug! Sorry about this, but for the time being I'm focused on supporting the latest versions of all browsers only. I'd accept a PR to support Firefox 52 ESR, but it's not currently a priority for this project.

**Comment by KellerFuchs** [comment]
@nolanlawson I'm not sure this is a Firefox bug; TBB uses a large number of patches to apply stricter security and privacy policies.

**Comment by nolanlawson** [comment]
Sorry, supporting Tor Browser is not a priority at the moment. I tested it out and confirmed that it is still not working though and that the error is the same as above.
