### ISSUE TITLE
Self-hosted Pinafore instances should report their own custom URL

### ISSUE THREAD

**Issue by nipos** [nolanlawson/pinafore#36]
If I create an toot using the instance https://pinafore.photog.social the public Mastodon toot page says it was created using Pinafore and links that text to https://pinafore.social.
Shouldn't it link directly to the instance which was used to create the toot?
Other people could see that note and it would help the decentralization if that note links to different instances and not only the official one.
As the correct link must be configured for the callback from the OAuth login page it should be easy to use the same address for the footer note.

**Comment by nolanlawson** [comment]
Hmm, I believe the point of this is to show the "app" that sent the toot? If I'm not mistaken, apps like Tusky and Amaroq do the same thing.

**Comment by nightpool** [comment]
@nolanlawson i think the thing they're saying is that they're not *using* pinafore.social, the app. they're using their own deployment, pinafore.photog.social, and expect that the app records created by that deployment link back to the app that made them.

**Comment by nightpool** [comment]
(this is different from, e.g. tusky and amaroq, since you can't self-host those)

**Comment by nolanlawson** [comment]
Ohhhh my bad. Yes we should use the URL that it's actually hosted at.

**Comment by codl** [comment]
should this be opt-in? I'm worried that people setting up private pinafore installs will end up unwittingly broadcasting their install's URL to everyone

**Comment by nipos** [comment]
An option to disable that makes sense in my opinion but I would prefer an opt-out solution.
The default should be the install which was really used to compose the toot and alternatively it could be set to link the pinafore.social as official install.

**Comment by nolanlawson** [comment]
I'm going to leave this as an exercise to the reader. Those who fork Pinafore are free to change the website that is reported if they'd like.
