### ISSUE TITLE
Client-side filters

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#369]
This includes the features:

- filter notifications by type (boost/favorite/follow/etc.)
- filter timelines by "show boosts: yes/no", "show replies: yes/no"
- regex filters

Currently this is not super easy to implement, because I made the decision early on to store all timelines as a list of string IDs. The statuses are then fetched on-demand from the IDB database. The goal was to minimize memory usage while allowing for infinite-scrolling lists and stored scroll positions.

There are a few potential solutions:

1. use full status/notification objects instead of status/notification IDs (sacrifice memory in favor of CPU, make the code a lot simpler)
2. continue using ID strings but fetch statuses on-demand from the DB when filtering (sacrifice CPU in favor of memory, make the code a lot more complex)
3. use a small summary object containing only the necessary fields for filtering (isBoost, isReply, notification type, etc.), continue fetching statuses on-demand but for filtering we can just use the summary objects (add some memory overage, CPU remains roughly the same, code for filtering should be fairly simple)

I'm in favor of # 3 personally but I also ought to actually measure memory usage to see how much I'm gaining from the current system. It's possible that I've done a premature optimization that is making things harder than necessary.

**Comment by nolanlawson** [comment]
Related: #6

**Comment by NelsonMinar** [comment]
Wanted to put in a thumbs up for "show boosts: no" as an option. It's the feature I miss most vs. using the stock UI.

**Comment by nolanlawson** [comment]
I think this should be implemented using option # 3 described above. So this would entail switching from a list of string IDs to a list of small summary objects to represent the timeline.

**Comment by nolanlawson** [comment]
I did a little research into this. It seems that there are two types of filters:

- word filters, for which there is a [documented API](https://docs.joinmastodon.org/api/rest/filters/) and which sync with the web UI
- type filters (e.g. "show boosts"/"show replies" on the Home timeline, and "boosts"/"favorites"/"follows"/"mentions" in the Notifications timeline) which sync between _instances of the web UI_ using an undocumented API at `/api/web/settings`.

It seems that Tusky has implemented the first one (https://github.com/tuskyapp/Tusky/pull/956) but not the second.

**Comment by strypey** [comment]
A couple of UX suggestions related to this:
* tweak the notifications tab so that when a post is boosted or favourited a lot, it only appears in the notifications once, the most recent time for each. Maybe with a settings checkbox to toggle this on and off? Even if a post in the notifications had a complete list of every user its been boosted/ favourited by above the post text, it would still take up *much* less space in the timeline than a complete notification for each boost or favourite. 
* having a drop-down of some kind to show previous boosters/ favouriters would be even better.

**Comment by nolanlawson** [comment]
@strypey Thanks for the suggestions, I agree it would be nice to collapse notifications in the UI. I miss that from Twitter.

I'm going to break this up into three separate issues to make it more manageable.

**Comment by strypey** [comment]
Just wanted to pop in a note saying how much I appreciate being able to sort DMs into their own timeline, and view @mentions separately from boosts/ favourites. Loving Pinafore more all the time!
