### ISSUE TITLE
Incoming statuses/notifications are unreliable

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#390]
Sometimes new notifications don't show up until you refresh. I've observed this in mobile Firefox on Android especially. Also I don't believe we're properly handling read vs unread states for notifications.

**Comment by pwFoo** [comment]
I get no push notifications from mastodon.social or  pinafore.social with chrome for android.

How should closed browser notification Work? Is it web notification api / service-worker.js based? That works fine with mobile clients like telegram, Google+, ...

**Comment by nolanlawson** [comment]
Push notifications are covered over in #19 

For this issue, it's more around non-push stuff. E.g. one issue I can think of is that closing a mobile browser and then reopening it hours later seems to not show updated notifications even if you're on the notification tab. Some kind of page lifecycle thing I need to set up correctly.

**Comment by nolanlawson** [comment]
duplicate of #14
