### ISSUE TITLE
Pinafore showing network errors for mastodon.technology

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#394]
Whenever I navigate between columns, it shows a network error: "failed to fetch." Seeing this in Firefox and Edge. It only seems to happen for mastodon.technology. :confused:

**Comment by nolanlawson** [comment]
OK this is a CORS bug in mastodon.technology. I'll let @ashfurrow know.

Repro:

```bash
curl 'https://mastodon.technology/api/v1/apps' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: https://dev.pinafore.social' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36' -H 'Access-Control-Request-Headers: content-type' --compressed
```

Looks like it's returning two `Access-Control-Allow-Origin` headers:

![2018-06-14 13_13_52-ubuntu](https://user-images.githubusercontent.com/283842/41435841-e67da414-6fd4-11e8-8826-14ba1fd8e732.png)

**Comment by ashfurrow** [comment]
I only had one header added in the nginx config, I think Mastodon might be adding its own header to certain API responses or something. I'm not sure, I've removed the header from nginx and the site appears working (I added it recently to prevent other warnings, but it looks like it's working fine without it now). Thanks for bringing this to my attention, sorry for the trouble!

**Comment by nolanlawson** [comment]
No prob. And yeah I think Mastodon adds CSAO header for certain endpoints, such as `/api`. That was probably it!
