### ISSUE TITLE
Proposal: Center navigation on bigger screens

### ISSUE THREAD

**Issue by nickcolley** [nolanlawson/pinafore#403]
At the moment on bigger screen's the navigation is far away from the main timeline.

We could consider centering this, what do you think?

Minimum would be to center align the items, or could do more:

![image](https://user-images.githubusercontent.com/2445413/41812633-973991c8-771e-11e8-8b25-c0da6d714840.png)

**Comment by nickcolley** [comment]
Simplest change:

![image](https://user-images.githubusercontent.com/2445413/41812723-e3941524-771f-11e8-8095-6a1cf6d9b5f6.png)

**Comment by nolanlawson** [comment]
I think for big screen this is reasonable. We could add a media query to set the nav items to be centered. LGTM!

**Comment by rylancates** [comment]
@nolanlawson - I'd love to see this implemented and am happy to jump in and help out.

Currently, I see that the app maintains a full width navbar up to 991px. At >991px, the navbar is no longer full width, and becomes left-justified.

Might I go forward under the assumption that you'd be in approval of center-justifying the navbar at >991px?

**Comment by nolanlawson** [comment]
@rylancates Sounds reasonable to me.
