### ISSUE TITLE
Unable to add instance "kinky.business"

### ISSUE THREAD

**Issue by LordMicroMan** [nolanlawson/pinafore#404]
I am unable to add instance "kinky.business" to my list of instances.
I have disabled all browser extensions and tried other browsers but it still fails to work.

![image](https://user-images.githubusercontent.com/40532714/41815780-438696b4-77a7-11e8-8059-7cb476d3c3bd.png)

**Comment by nolanlawson** [comment]
Thanks for filing the issue! It looks like this is an issue with how kinky.business's server headers are set up:

```
$ curl -sLv kinky.business/api/v1/instance -o /dev/null
...
Access-Control-Allow-Origin: https://kinky.business/
...
```

That `Access-Control-Allow-Origin` would need to be set to `*` (as it is with most Mastodon/Pleroma instances) in order for Pinafore to be compatible with it. If you contact your server admin they should be able to fix it. :)
