### ISSUE TITLE
focus is unpredictable when following top-bar links

### ISSUE THREAD

**Issue by technomancy** [nolanlawson/pinafore#409]
When you click on a link in the top bar, (home, notifications, etc) scrolling with the keyboard (arrow keys and pageup/pagedown) stops working, presumably because focus is on the wrong thing. Pressing tab seven times fixes this, but that's kind of an annoying workaround. Sometimes clicking on the top bar doesn't have this problem, but I can't figure out what the pattern is for when it breaks and when it works.

Earlier versions had this focus problem upon the initial page load, but that seems to have gone away, so thanks for fixing that.

This is pretty much my only complaint about Pinafore, which has been a real improvement over the default Mastodon web UI for me, so thanks for putting it together!

**Comment by nolanlawson** [comment]
I don't quite understand what the issue is. I tried to reproduce it in Firefox and I cannot. Is it a browser-specific issue? Can you provide the steps to reproduce?

Also yeah focus is saved on individual link items (e.g. usernames, hashtags, etc.) so that when you press the back button you not only scroll to the right point in the timeline but also have the right element focused (for keyboard users). Is that not working for you?

**Comment by technomancy** [comment]
Sure. (I'm using Firefox 61 on Debian.)

On a fresh load of https://pinafore.social, scrolling works fine. I can use the arrows or pageup/pagedown. If I click on the notifications tab, suddenly pressing the arrows or using pageup/pagedown have no effect. I can get them back by pressing tab repeatedly. Navigating back to the home tab has the same problem; none of the scrolling keys work until I either press tab several times or click somewhere off the top bar.

The only reason this is a problem is that I use a keyboard-driven extension (SurfingKeys) so I only rarely use the mouse and its scroll wheel. But this problem is still present when SurfingKeys is disabled.

**Comment by nolanlawson** [comment]
Hmmm, isn't this the intended behavior though? I believe Mastodon itself in single-column mode does the same thing. If you click on a button in the navigation bar, the focus is now on that button, so you should normally be unable to scroll up or down with the up/down/pageup/pagedown arrows.

I'm not a huge a11y expert though, so please do correct me if I'm wrong. :)

**Comment by technomancy** [comment]
I'm not sure what the intended behavior is, but the default Mastodon client's poor support for keyboard-driven browsing is the primary reason I don't use it, so I'd hesitate to consider it an exemplar.

In my mental model, the home tab and the notification tab are different pages, and the fact that they're implemented without a full page refresh is just an implementation detail I shouldn't have to think about. So navigating from notifications back to home should put the site in the same state as the initial page load. But maybe that's an unrealistic expectation?

**Comment by MarcoZehe** [comment]
Initially, when loading https://pinafore.social, focus does indeed not go to the top of the page, but is auto-focused somewhere further below, like my screen reader usually starts at the h1 that is the Compose Toot heading. So initial page load does have a focus set that skips past the tabs at the top and thus possibly enables arrow keys and scrolling.

If I then press any of the tabs, focus does get caught at the top, like:

1. Click Notifications.

Focus stays in the top bar, does not get redirected to the heading.

2. Click Home.

Focus stays at the top, does not go to the Compose Tot heading as after the initial page load.

**Comment by nolanlawson** [comment]
> When you click on a link in the top bar, (home, notifications, etc) scrolling with the keyboard (arrow keys and pageup/pagedown) stops working, presumably because focus is on the wrong thing. 

At some point this seems to have been fixed. When I first load pinafore.social, I can scroll down with either PageDown (which does a normal scroll) or Down (which uses the keyboard shortcut style where it focuses one toot at a time). After I click a navigation button, I have the same experience. (At least in Firefox and Chrome.) So this seems fixed to me.

**Comment by technomancy** [comment]
Thanks; I can confirm it's working great now. Nice work!
