### ISSUE TITLE
Alt text does not apply to image

### ISSUE THREAD

**Issue by bvtsang** [nolanlawson/pinafore#41]
I tried to [add alt text to an image](https://icosahedron.website/@bvtsang/99830853571376431), but it renders as "undefined".

My testing thread is at https://icosahedron.website/@bvtsang/99830825277167424

**Comment by nolanlawson** [comment]
Oops, this is a bad bug and probably related to the spoiler wrapped around the image. Thanks for reporting.

**Comment by nolanlawson** [comment]
Wait, are you saying you posted it _from_ Pinafore and the alt is undefined, or you're viewing it _on_ Pinafore and the alt is undefined?

**Comment by nolanlawson** [comment]
Oof, okay I see that Mastodon shows it as undefined. Yeah this needs to be fixed ASAP.

**Comment by bvtsang** [comment]
To clarify, I posted it from Pinafore and the alt text is undefined. The screenshot was taken before I posted it.
