### ISSUE TITLE
Sync with latest Sapper

### ISSUE THREAD

**Issue by Rich-Harris** [nolanlawson/pinafore#416]
Hey — notwithstanding the [issues you've raised that are still open](https://github.com/sveltejs/sapper/issues/created_by/nolanlawson), I wanted to see what changes would be required to get Pinafore using sveltejs/sapper so that you don't need to maintain a fork.

It looks like [most of the changes](https://github.com/nolanlawson/sapper/commits/for-pinafore-7) should be fairly easy to backport, and some of them may no longer be relevant (for example, routes are no longer preloaded automatically, you have to [explicitly call `prefetchRoutes(...)`](https://sapper.svelte.technology/guide#prefetchroutes-routes-)). If I get time later I'll make individual issues for them on top of the existing ones.

I mention this because we just put out Sapper 0.15 which improves the routing quite a bit — I remember one of your bits of feedback was that it was annoying to have to recreate the nav etc from scratch upon navigation; routes are now hierarchical and allow persistent [layout](https://sapper.svelte.technology/guide#layouts) at any level (root or nested).

**Comment by nolanlawson** [comment]
Yup, this is something I would definitely like to do. I think I've made so few modifications to Sapper that it really ought to be straightforward. I'm also looking forward to the perf improvements from not re-rendering the whole app frame on every navigation.

I'm taking a break from OSS for the summer, though, so may not get on this soon. But thanks for the poke in the right direction, and for all the work on Svelte/Sapper! 😃

**Comment by nolanlawson** [comment]
itshappening.gif :tada:
