### ISSUE TITLE
Double Posting: Control+Enter Doesn't Disable

### ISSUE THREAD

**Issue by Fidgetcetera** [nolanlawson/pinafore#421]
If you use control+enter to post, you can hit control+enter multiple times while the toot button still has a loading bar over it and the text is still in the field, and it will repeat the post as many times as you hit it during that time.

Soooo, you can REALLY easily either accidentally or intentionally spam a feed. Or just accidentally double post.

**Comment by nolanlawson** [comment]
good catch, this needs fixing!
