### ISSUE TITLE
Page contents will overflow on <620px wide / Chrome on PC

### ISSUE THREAD

**Issue by unarist** [nolanlawson/pinafore#422]
Timelines and the compose box will overflow when window width is smaller than 620px, and the character counter is under the vertical scrollbar.
 
![image](https://user-images.githubusercontent.com/705555/44137687-3de89ca6-a0ac-11e8-9029-6482726a28ef.png)

Chrome 68.0.3440.106 / Windows 10

**Comment by mattcoxonline** [comment]
Same for me using Vivaldi (Chrome) on Mac.

![pinafore](https://user-images.githubusercontent.com/673542/44204947-fab08f80-a154-11e8-9406-489db1028fa5.gif)

**Comment by nolanlawson** [comment]
Yes I think I assume a min width of 620 pretty frequently across the UI, at least for desktop browsers. Not sure how to go about fixing it but it's a bug for sure.

**Comment by nolanlawson** [comment]
I've done some work recently to make Pinafore work well even on KaiOS devices (240x294 pixels), and I can't repro the egregious examples shown above, so I'm going to mark as closed for now. Thanks for reporting!
