### ISSUE TITLE
Even after disabling chrome extensions like Privacy Badger and uBlock origin, still getting timeouts

### ISSUE THREAD

**Issue by smokinjoe** [nolanlawson/pinafore#439]
So I wanted to get pinafore working (https://pinafore.social) ran into some issues due to a couple extensions that I believe was messing with whatever background scripts needed to work.

However, after disabling the two extensions (Privacy Badger and uBlock origin), I was still getting timeout errors. I ended up needing to open up the chrome console and enter `localStorage.clear()` before I was able to add the mastodon instance and my account.

Just a heads up that perhaps some fix may be needed to clear out localStorage a little more aggressively when adding a new mastodon instance.

**Comment by smokinjoe** [comment]
I'll do my best to find some free time and take the opportunity to get into the Mastodon dev game by helping out with a PR.

**Comment by nolanlawson** [comment]
Closing old issues, please reopen if you can still reproduce! Thanks.
