### ISSUE TITLE
[Feature] keyboard navigation

### ISSUE THREAD

**Issue by joachimesque** [nolanlawson/pinafore#474]
I'd like to be able to navigate with `j` and `k` in timelines. `j` for next post, and `k` for previous. Ideally, l would be used to like the active post, `o` to open it, `r` and `b` to reply and boost it.

To see such a feature in action, check out the Mastodon UI or Reddit (old and new versions).

**Comment by szermatt** [comment]
Sorry for the spam; I hadn't realised that a commit in my own fork would appear here. I'm working on a pull request for this issue, but it's not ready yet.

**Comment by nolanlawson** [comment]
fixed in https://github.com/nolanlawson/pinafore/pull/870, thank you @szermatt !
