### ISSUE TITLE
It could be easier to switch between accounts!

### ISSUE THREAD

**Issue by Cassolotl** [nolanlawson/pinafore#48]
Hello. :) So I read the contributor guidelines, and I understand that this might be an issue that it's too early-days for and you might not respond, which is totally fine.

First of all, this is very nice to use! I love the dark text on the light background, too. My feedback is just that it takes a lot of clicks/taps to switch between accounts - *Settings > Instances > [Instance] > "Switch to this instance" > Home.* So a way to make that a little faster, and maybe even a way to change which account you're posting to from the "New Toot" text box area, could be really nice!

Thank you for your hard work on this, the results so far are LOVELY.

**Comment by mlcdf** [comment]
related to https://github.com/nolanlawson/pinafore/issues/48

**Comment by Cassolotl** [comment]
Oh yeah, I think mine is a duplicate. :) Thanks, I'll close this!
