### ISSUE TITLE
opening cybrespace custom emoji locks up pinafore

### ISSUE THREAD

**Issue by nightpool** [nolanlawson/pinafore#49]
Pixel 2, Chrome 65.0.3324, installed as a PWA. Also confirmed on Chrome 65, ubuntu linux

The entire site locks up, leading to the app needing to be force-closed (on mobile), or displaying the "oh snap!" page on chrome.

of note is that we have lots of emoji (339) and a couple that are broken (for unknown reasons, the asset urls return 403s)

**Comment by nightpool** [comment]
it *seems* like setting the broken emoji to "unlisted" fixes this problem, but because of the way this issue seems to interact with the service worker caching (only happens when emoji are uncached, maybe?) i can't say for sure that that's the issue

**Comment by nolanlawson** [comment]
Yeah I think the UI was not designed for that many emoji. I'll create a cybre.space account to test, and then use a virtual list to fix this. (I stupidly did not use a virtual list for custom emoji, because I didn't expect there to be so many. 🙃)

**Comment by nightpool** [comment]
i'm honestly wondering if this has more to do with the broken emoji though..... I've set them to unlisted for now, and haven't had a problem since (although the majority of emoji just don't display images at all in the picker which muddles the situation a little)

**Comment by nolanlawson** [comment]
Hmmm yeah that would make sense to me, since it doesn't feel like 400 emoji should feel all that different from 50 emoji. So in any case, is this fixed now for cybre.space users?

For the emoji that don't display images, what's going on with those? Any chance I can get a cybre.space account to test? (Feel free to DM me at @nolan@toot.cafe if this is possible. 🙂 )

**Comment by nightpool** [comment]
uhhh sure let me visible them real quick

**Comment by jemus42** [comment]
Uhm, is this related to custom emoji not being rendered?

Compare pinafore:
![](https://dump.jemu.name/2018-08-toe86pxiohnhw6k.png)

With the default web interface:
![](https://dump.jemu.name/2018-08-z6pw667orsvbdfz.png)

**Comment by nolanlawson** [comment]
@jemus42 No, that's a separate issue and should be fixed in the latest now.

Closing this issue since I'm not sure we can repro anymore.
