### ISSUE TITLE
Ios Progressive Web App for audio-recording  navigator.mediaDevices.getUserMedia() is undefined

### ISSUE THREAD

**Issue by Aman1324** [nolanlawson/pinafore#534]
I am currently working on progressive web app to record audio and playing it. Its working in safari and chrome browser but when i add it to my ios home screen to make it as webApp, I got this error  **An error occurred: – "undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia())**. In mac safari browser and iphone safari browser its not giving any error. can you give me any suggestion how to resolve it ?

**Comment by nolanlawson** [comment]
As I understand it, this is not related to Pinafore? Sorry, but I'm not sure about this. You might try StackOverflow instead.
