### ISSUE TITLE
SyntaxError: Cannot declare a let variable twice: 'e' (inside of Fluid.app)

### ISSUE THREAD

**Issue by zachleat** [nolanlawson/pinafore#546]
https://fluidapp.com/ runs Safari 11 (on my local machine) as an app wrapper for web sites. It throws a JS error when trying to add an instance on Pinafore.

![image](https://user-images.githubusercontent.com/39355/45572062-e7fda900-b82d-11e8-9b0c-09124ecec6df.png)

![image](https://user-images.githubusercontent.com/39355/45572069-edf38a00-b82d-11e8-9b28-44c632a7a2d3.png)

Results in an inability to add an instance: the Log in button never grays out and hitting ENTER goes to a broken page

![image](https://user-images.githubusercontent.com/39355/45572136-0fed0c80-b82e-11e8-8e60-bcb05b78f969.png)

Consolation is that it works fine in Safari 11 standalone.

![image](https://user-images.githubusercontent.com/39355/45572155-1f6c5580-b82e-11e8-8c17-a000f508c5d4.png)

Dunno if this is worth fixing, but I’d love for Pinafore to work in Fluid.app

**Comment by nolanlawson** [comment]
Strange! It looks like some kind of minification error. I'll look into this.

**Comment by nolanlawson** [comment]
Looks like I just need to enable the `safari10` setting in Uglify/Terser: https://github.com/mishoo/UglifyJS2/issues/1753

**Comment by zachleat** [comment]
Awesome, thank you!

This might be a rats nest but I still wasn’t able to get it to work. Feel free to ignore this, I’ll just use my regular web browser to access Pinafore. Fluid.app must have some edge cases to it

![image](https://user-images.githubusercontent.com/39355/45951986-2aac4780-bfcb-11e8-8800-dbd97aab5045.png)

(these errors appear on page load, not on the Add Instance workflow—although I am still not able to add an Instance)

Anyway, like I said—appreciate the help, probably not worth sinking more time into it ❤️

(Love Pinafore, thanks)
