### ISSUE TITLE
Cannot add instance: IndexedDB error ("mutation operation was attempted")

### ISSUE THREAD

**Issue by djoerd** [nolanlawson/pinafore#58]
Pinafore gives the following error when adding an instance (such as "mastodon.social") on Firefox 59.0.2 on Ubuntu 16.04 :

    Error: undefined. Is this a valid Mastodon instance?

Here's part of the error message in the console ("A mutation operation was attempted on a database that did not allow mutations."):

    error​bubbles: true​cancelBubble: false​cancelable: true​composed: false​currentTarget: null​defaultPrevented: false​eventPhase: 0​explicitOriginalTarget: IDBOpenDBRequest​​error: DOMException​​​code: 11​​​columnNumber: 0​​​data: null​​​filename: ""​​​lineNumber: 0​​​message: "A mutation operation was attempted on a database that did not allow mutations."​​​name: "InvalidStateError"​​​result: 2154168326​​​stack: ""​​​__proto__: DOMExceptionPrototype​​​​ABORT_ERR: 20​​​​DATA_CLONE_ERR: 25​​​​DOMSTRING_SIZE_ERR: 2​​​​HIERARCHY_REQUEST_ERR: 3​​​​INDEX_SIZE_ERR: 1​​​​INUSE_ATTRIBUTE_ERR: 10​​​​INVALID_ACCESS_ERR: 15​​​​INVALID_CHARACTER_ERR: 5​​​​INVALID_MODIFICATION_ERR: 13​​​​INVALID_NODE_TYPE_ERR: 24​​​​INVALID_STATE_ERR: 11​​​​NAMESPACE_ERR: 14​​​​NETWORK_ERR: 19​​​​NOT_FOUND_ERR: 8​​​​NOT_SUPPORTED_ERR: 9​​​​NO_DATA_ALLOWED_ERR: 6​​​​NO_MODIFICATION_ALLOWED_ERR: 7​​​​QUOTA_EXCEEDED_ERR: 22​​​​SECURITY_ERR: 18​​​​SYNTAX_ERR: 12​​​​TIMEOUT_ERR: 23​​​​TYPE_MISMATCH_ERR: 17​​​​URL_MISMATCH_ERR: 21​​​​VALIDATION_ERR: 16​​​​WRONG_DOCUMENT_ERR: 4​​​​code: Getter​​​​​<get>: code()​​​​​​length: 0​​​​​​name: "get code"​​​​​​__proto__: ()​​​​​​​apply: apply()​​​​​​​​length: 2​​​​​​​​name: "apply"​​​​​​​​__proto__: ()​​​​​​​​​apply: apply()​​​​​​​​​​length: 2​​​​​​​​​​name: "apply"​​​​​​​​​​__proto__: function ()​​​​​​​​​arguments: null​​​​​​​​​bind: function bind()​​​​​​​​​call: function call()​​​​​​​​​caller: null​​​​​​​​​constructor: function Function()​​​​​​​​​length: 0​​​​​​​​​name: ""​​​​​​​​​toSource: function toSource()​​​​​​​​​toString: function toString()​​​​​​​​​Symbol(Symbol.hasInstance): undefined​​​​​​​​​__proto__: Object { … }​​​​​​​arguments: null​​​​​​​bind: function bind()​​​​​​​call: function call()​​​​​​​caller: null​​​​​​​constructor: function Function()​​​​​​​length: 0​​​​​​​name: ""​​​​​​​toSource: function toSource()​​​​​​​toString: function toString()​​​​​​​Symbol(Symbol.hasInstance): undefined​​​​​​​__proto__: Object { … }​​​​columnNumber: Getter​​​​constructor: function ()​​​​data: Getter​​​​filename: Getter​​​​lineNumber: Getter​​​​message: Getter​​​​name: Getter​​​​result: Getter​​​​stack: Getter & Setter​​​​__proto__: Object { … }​​onblocked: function onblocked()​​onerror: function ()​​onsuccess: function onsuccess()​​onupgradeneeded: function onupgradeneeded()​​readyState: "done"​​source: null​​transaction: null​​__proto__: IDBOpenDBRequestPrototype { onblocked: Getter & Setter, onupgradeneeded: Getter & Setter, … }​isTrusted: true​originalTarget: IDBOpenDBRequest { onblocked: onblocked(), onupgradeneeded: onupgradeneeded(), readyState: "done", … }​target: IDBOpenDBRequest { onblocked: onblocked(), onupgradeneeded: onupgradeneeded(), readyState: "done", … }​timeStamp: 22288​type: "error"​__proto__: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … } addInstance.js:46

**Comment by djoerd** [comment]
Update: It works in Chromium

**Comment by nolanlawson** [comment]
Hmm I've seen this issue from multiple folks, and it seems there are a few things that can cause it:

- Privacy Badger (#23)
- private browsing (#30)
- Firefox "never remember history" setting

You might try disabling those (or whitelisting your instance in Privacy Badger) and then trying again. Also check any other extensions you may have installed in Firefox.

**Comment by daquinons** [comment]
I'm having that same problem but I don't see in my console the "mutation operation was attempted" message. I see, before adding the instance, this one though:

"TypeError: ServiceWorker script at https://pinafore.social/service-worker.js for scope https://pinafore.social/ encountered an error during installation."

I've checked the private options and remember history, and they are both correctly set. I've also disabled manually my extensions and used the "Safe mode" disabling all settings and extensions. The result was the same 😔 Let me know if you need something to debug

**Comment by nolanlawson** [comment]
Hmm that sounds like a totally different error. It sounds like the service worker script hit an error, but I'd have to see what that error was in order to understand how to fix it… 😕

In Firefox you can unregister service workers by going to about:debugging#workers. Search for "pinfaore" in there and just unregister them all. Then clear browser cache / site data, and hopefully it should work again! If not please do send me a screenshot of the service worker error if you're able to capture it.

**Comment by nolanlawson** [comment]
With #733 we now detect localStorage/IndexedDB errors and show a warning for it.
