### ISSUE TITLE
Instance switching button is below the fold

### ISSUE THREAD

**Issue by stuartlangridge** [nolanlawson/pinafore#583]
I didn't realise for a little while that one has, after adding a second instance, to explicitly _switch_ to it with the "Switch to this instance" button in the settings. This might be solved by having easier instance switching overall (which is #11), but in the interim, moving the "Switch to this instance" button _above_ the Theme colour chooser may make it more obvious that this button exists and needs pressing (because it's below the fold and must be scrolled to at the moment). I certainly think that, if I've chosen a new instance from the instance chooser, that I'm more likely to want to switch to it than I am to want to set its theme colour when I'm not even looking at it.

**Comment by nolanlawson** [comment]
I think this is somewhat fixed by #945. Arguably we should make it even easier to switch instances (#11), but I think that gets us a bit closer, and reduces the pain of the instance switching buttons being below the fold. Thanks for reporting!
