### ISSUE TITLE
Basic feature parity with Mastodon web UI

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#6]
To reach basic parity with the Mastodon web UI, we need these features:

- [x] mention someone from their profile page
- [x] block/unblock accounts
- [x] mute/unmute accounts
- [x] authorize/reject follow requests
- [x] show list of followers/following on account profile
- [x] pin/unpin toots
- [x] mute conversation
- [x] hide boosts from someone
- [x] block/unblock instances
- [x] show client that posted a toot (web/Amaroq/etc)
- [ ] report toots
- [ ] confirmation dialogs for deleting/boosting/blocking/muting/etc
- [ ] confirmation to also mute notifications when muting someone
- [ ] media focal points
- [ ] opengraph cards
- [ ] edit profile
- [ ] edit lists
- [ ] paginate list of accounts beyond 80
- [ ] close/open all CWs in a thread at once
- [ ] embed a status

**Comment by skiant** [comment]
Question about the "Mute notifications" line, do you mean the ability to mute specific notifications (likes/boosts) or a general "nuke them all" option? Because I'd be definitely interested in the former!

**Comment by nolanlawson** [comment]
@skiant When you mute someone in Mastodon, you have the option to also mute notifications from them. (There's a little popup to confirm before you mute.)

**Comment by jemus42** [comment]
Should the additional profile metadata blocks be on this list? I kinda miss seeing those :/

**Comment by nolanlawson** [comment]
@jemus42 that's over in #454 and it's now fixed! :)

**Comment by nolanlawson** [comment]
I'm going to close this issue and open individual issues for the remaining features.
