### ISSUE TITLE
Drag/drop images onto the compose text box to upload

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#65]

**Comment by Fidgetcetera** [comment]
Would it be helpful to bring up on this issue that you also cannot paste images from the clipboard to upload in pinafore? It seems relevant enough to this issue that I didn't want to make a separate one.

**Comment by nolanlawson** [comment]
Opened: https://github.com/nolanlawson/pinafore/issues/179

**Comment by spriteclad** [comment]
Has this been worked on yet? This is one of the few features that would allow me to use Pinafore more often.
