### ISSUE TITLE
Copyable links in Pinafore are to Pinafore

### ISSUE THREAD

**Issue by stuartlangridge** [nolanlawson/pinafore#653]
The links to individual toots in Pinafore are to show that toot _in_ Pinafore. This means that I can't copy one of those links and send it to someone else who isn't a pinafore user, because they then have to log in to see the link. It would be much nicer if these links were to the actual toot on its instance; if it's important that I myself be able to tap them then overriding the URL with JavaScript so that its href starts pointing at the canonical URL for that toot but a tap shows it in Pinafore ought to be easy enough.

**Comment by stuartlangridge** [comment]
![1542413655-picsay](https://user-images.githubusercontent.com/4356350/48653618-69c0ad00-e9fe-11e8-9c77-c5a8aa961d25.jpg)

**Comment by nolanlawson** [comment]
I believe overriding permalinks when you click on them would be too complicated given the current Svelte architecture. However, the way this is currently handled is that permalinks appear when you click on the toot itself (and are indicated with a little icon showing a box with an arrow sticking out of it). You can also click the … and choose "Copy Link", and it will copy a permalink.

Hope that helps; I agree it's a bit annoying though! FWIW, the main mastodon web client also has this problem; links in the URL bar cannot be shared with other users unless they are on the exact same Mastodon instance.
