### ISSUE TITLE
Image modals look blurry

### ISSUE THREAD

**Issue by codl** [nolanlawson/pinafore#71]
I think this is due to the transform on `.modal-dialog-content` causing it to land inbetween pixels

compare:

![2018-04-11t08-46-53-0ooo](https://user-images.githubusercontent.com/315139/38600740-77192b26-3d65-11e8-842b-fb7c73c14302.png)
![2018-04-11t08-49-01-00o0](https://user-images.githubusercontent.com/315139/38600717-6741c604-3d65-11e8-80f6-d0ce1040c06e.png)

here's that test post: <https://chitter.xyz/@codl/99839461965520912>

**Comment by nolanlawson** [comment]
Is this on a Chromium-based browser?

**Comment by codl** [comment]
yup this is chrome 65

**Comment by nolanlawson** [comment]
Just tested that toot, and the blurriness only seems to occur in desktop Chrome and Safari. Firefox and Edge aren't blurry.
