### ISSUE TITLE
Set default theme based on prefers-color-scheme

### ISSUE THREAD

**Issue by sorin-davidoi** [nolanlawson/pinafore#728]
[Link to standard draft](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme).

Currently only supported by [Safari Technology Preview >= 68](https://developer.apple.com/safari/technology-preview/release-notes/).

**Comment by nolanlawson** [comment]
Hmm, which dark theme should be default, though? I guess Ozark because it's first?

**Comment by sorin-davidoi** [comment]
Ozark or Pitch Black seem like good choices.

**Comment by Hund** [comment]
This does not work for me on Android with Firefox 96.1.1.
