### ISSUE TITLE
feature req: click the current tab to expand new statuses

### ISSUE THREAD

**Issue by codl** [nolanlawson/pinafore#73]
when scrolled down, new statuses are collapsed into a "show N more" button. when scrolling back up by clicking the current tab, i usually want to see those statuses, but my mouse cursor is *so far away from that button ahhh*

i think those statuses should be expanded on the second click on the current tab (when the page is already scrolled up)

precedent: twitter does this, except they expand on the first click when scrolling up (which tends to confuse me 😵)

**Comment by nolanlawson** [comment]
Sorry for not responding sooner. There is now a keyboard shortcut for this: you can use the "." key to show the toots hidden behind the button. Let me know if this solves the issue for you!

**Comment by codl** [comment]
A keyboard shortcut is nice but i was hoping for something faster. After having scrolled up by clicking the tab, moving my hand to the keyboard isn't faster than moving my mouse cursor to the show N more button

**Comment by nolanlawson** [comment]
@codl If you press the "." key then it will both scroll up to the top and show new messages. :)
