### ISSUE TITLE
feature req: option to always put new statuses into the "show N more" thing

### ISSUE THREAD

**Issue by codl** [nolanlawson/pinafore#74]
I'd like an option to disable streaming statuses and notifications into the tl, instead always putting them in the "Show N more" button like when statuses come in when you are scrolled down the page

I even think it could be on by default. As opposed to the main mastodon webapp, pinafore isn't really a dashboard-type ui so it leads to more of a: "tab in, look at what you missed, tab out" workflow, I think? not really a "sit back and watch the updates roll in" kinda thing.

Also having statuses stream in is kind of stressful for me, and for others too from what I've heard

precedent: most timeline-based services and their apps (twitter, tumblr..) don't stream, and just poll every minute or so but the result is the same

**Comment by nolanlawson** [comment]
Seems reasonable to add an option. I kinda feel like most folks are used to the "always streaming" functionality, though, even if Pinafore isn't very dashboard-like. :)

**Comment by Oreolek** [comment]
This is already in, isn't it?

**Comment by codl** [comment]
if it is then I don't know where it is

**Comment by nolanlawson** [comment]
It's not.

**Comment by codl** [comment]
does #1253 implement this?

**Comment by codl** [comment]
looks like a yes to me 🙌 thank you @nolanlawson

**Comment by nolanlawson** [comment]
Yes, it does. :) I'll close this issue.
