### ISSUE TITLE
Close/open all CWs in a thread at once

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#744]
Copied from #6

Mastodon frontend already has this feature.

**Comment by forivall** [comment]
related keywords for searching this feature req: expand, show more

**Comment by jdaviescoates** [comment]
Yes, but I don't want to just be able to do this in a thread, I want to be able to do it for _all_ toots (like I can on Mastodon).

I basically never want to have to click "show more" and _always_ want to see content. 

I've got "Show sensitive media by default" checked in Settings, I'd like a similar setting for this please. Thanks! Other than this I much prefer the Pinafore look and feel than Mastodon.

**Comment by nolanlawson** [comment]
Dup of #1914, fixed by #1973

**Comment by nolanlawson** [comment]
@jdaviescoates Sorry for not noticing your comment, but this is already available in the Pinafore settings: "show sensitive media by default"

![Screenshot from 2021-03-13 17-33-31](https://user-images.githubusercontent.com/283842/111054533-5123fe80-8422-11eb-8865-e11bc486fc75.png)

**Comment by jdaviescoates** [comment]
@nolanlawson that setting doesn't appear to expand any toots that have a CW but no media.

**Comment by nolanlawson** [comment]
@jdaviescoates Ah I see, yes, that would have to be a new setting. Opened an issue: https://github.com/nolanlawson/pinafore/issues/1997
