### ISSUE TITLE
Running pinafore in a subfolder

### ISSUE THREAD

**Issue by captainark** [nolanlawson/pinafore#75]
Hi !

As a sysadmin, I love to self-host *all of the things*.

I was able to run pinafore without issue by following [the documentation](https://github.com/nolanlawson/pinafore/blob/master/CONTRIBUTING.md).

I prefer my webapps to run in a subfolder rather than on a subdomain. I'd like to be able to access Pinafore from mydomain.com/pinafore instead of pinafore.mydomain.com.

Is this possible at this time ? I could access the main page from behind a nginx proxy, but accessing mydomain.com/pinafore/notifications would redirect me to mydomain.com/notifications.

Thanks !

**Comment by nolanlawson** [comment]
This isn't currently possible due to how Sapper routing works. I think you may have to use rewrite rules at the Nginx/Apache level.
