### ISSUE TITLE
Pleroma issue with images

### ISSUE THREAD

**Issue by Sirikon** [nolanlawson/pinafore#750]
Hi there!

I'm trying to make Pinafore fully work with Pleroma, one of the issues is related with images as status attachments.

Pleroma doesn't seem to send metadata about attachments, this means there's no information about width or height of the images. And **pinafore uses this to set the image width and height**.

The result is: All images will show as width=300 height=200, which is the fallback size.

I understand a fallback size for images shown in the timelines (to prevent the scroll UI going back and forth during image loading), but... couldn't just use automatic size when opening the image inside the modal?

I know Pleroma compatibility is a "possible future goal", but this seems like a reasonable change for me and I could implement this in a PR if you're okay with it :)

This way, opening images in the modal would be full size, and improve the user experience for Pleroma users (and any other server technology for ActivityPub that doesn't send metadata about images).

**Comment by nolanlawson** [comment]
If Pleroma doesn't send the width/height for images then unfortunately that's a performance concern for Pinafore, because we rely on the width/height to calculate the layout size and avoid browser layout recalcs. The placeholder is also set to the same width/height of the image as the image loads.

I'm not sure how to fix this properly. Ideally Pleroma should just send this information so that clients can optimize their image layouts.

**Comment by Sirikon** [comment]
Totally understand. But I'm curious: Is it that bad to have automatic sizing on the image shown inside the modal? Because it's the main issue for me... Seeing images in the timeline tinier isn't a problem for me if clicking on them shows them full size.

Also, I'll check if Pleroma have some configuration to enable that, and check if the attachment meta is a standard thing or a Mastodon-only thing.

**Comment by nolanlawson** [comment]
This has actually changed now that we have fixed-size image mode (https://github.com/nolanlawson/pinafore/pull/747). It's not bad per se, but it's nice to have the option to lay out the images without downloading them first.

**Comment by Sirikon** [comment]
So, could be an option to use automatic sizing inside the image's modal when this mode is enabled?

**Comment by nolanlawson** [comment]
That mode applies to inline images, not images inside the modal. For images inside the modal, we assume the server is sending us a width and height. If Pleroma doesn't intend to implement that, then yeah we would need a workaround.

**Comment by Sirikon** [comment]
I'm in progress of setting up a Pleroma environment over Docker for easier deployment and testing this stuff easier.

Right now, at least, Pleroma doesn't send any metadata, not even with files uploaded to the instance itself and not federated.

If further investigation doesn't return anything, will leave an issue in their GitLab.

**Comment by Sirikon** [comment]
Just wrote an issue for them explaining this issue and another one: https://git.pleroma.social/pleroma/pleroma/issues/447 .

**Comment by Sirikon** [comment]
Seems that a workaround for this will be needed:
https://git.pleroma.social/pleroma/pleroma/issues/447#note_10122

"We won’t provide metadata as it’s not provided in ActivityPub and we won’t process attachments."
