### ISSUE TITLE
Provide an in app reload to apply updates when installed as a pwa

### ISSUE THREAD

**Issue by kepstin** [nolanlawson/pinafore#77]
I have pinafore installed as a pwa in Firefox Mobile (android). I got a popup message this morning saying that a client update was available, and it asked me to reload. However, the Firefox pwa interface does not expose a reload control, so it wasn't obvious what I should do.

**Comment by nolanlawson** [comment]
Unfortunately right now you have to open the app switcher, swipe to close the app, and then reopen it. I agree we should have a manual reload button for UIs that don't expose a reload button themselves.

**Comment by mlcdf** [comment]
I guess, the button could be added directly on the popup? I don't think of any other scenarios where the user might want to refresh the app.

**Comment by kepstin** [comment]
Putting the refresh on the popup is problematic, because I might decide to dismiss the popup and finish what I was doing before refreshing the client.

I think it would be nice if the refresh was transparent - could we have the client automatically refresh itself on the next time you do an action that switches context, like switching feeds, jumping to the top of a list, etc.?

**Comment by nolanlawson** [comment]
I'd rather not interrupt the user's work by trying to guess when they want to refresh... My thoughts were:

1. implement a new toast, which slides up from the bottom
2. the toast has a reload button on it
3. the toast also has an X button on it
4. the toast sticks around for longer than the regular toast (let's say 20-30 seconds)
