### ISSUE TITLE
in "grouped images" mode, the sensitive button should be the same size as media

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#771]
It's all a fixed size, so it's weird to click that button and see the size change.

**Comment by nolanlawson** [comment]
All the images are `width:100%;height:100%`, need to figure out how to apply that to the sensitive button

**Comment by sgenoud** [comment]
I should actually only depend on the width of the div and the number of images in the attachments.

https://github.com/nolanlawson/pinafore/blob/master/src/routes/_components/status/MediaAttachments.html#L33

Let me have a look.
