### ISSUE TITLE
Blank empty page with qutebrowser

### ISSUE THREAD

**Issue by Hund** [nolanlawson/pinafore#779]
I'm just met with an empty blank page, unless I disable JavaScript, then it just asks me to enable it. I'm running qutebrowser 1.5.2 with Qt WebEngine 5.11.1.

I'm not sure what to do?

**Comment by Hund** [comment]
It's Gentoo Linux. Qt WebEngine is based on the WebEngine from the Chromium project.

![pinafore](https://user-images.githubusercontent.com/320498/49815971-38bd6900-fd6d-11e8-86ee-59c146d6fa65.png)

**Comment by nolanlawson** [comment]
It looks like LocalStorage is disabled? Do you have some custom privacy settings or a browser extension?

**Comment by nolanlawson** [comment]
BTW this should be worked around in https://dev.pinafore.social. I implemented an in-memory shim over LocalStorage, although the downside is that Pinafore will not store any data for you and you will have to log in again every time

**Comment by Hund** [comment]
Oh! It was disabled, I don't know why, but enabling it again solved the issue. Thanks! :)
