### ISSUE TITLE
Enable CSP when exporting

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#796]
The issue is the inline script `nonce`s, which are different for every page. We could just use a single nonce, but then that's not really security, because it's the same nonce every time. :roll_eyes: 

We could also take the checksum of all the scripts and include those in the header, but since we have 25 separate pages plus the `service-worker-index.html`, that would be a huge header.

So in general I'm not sure how to solve this or if this even can be solved, but it's worth investigating.

**Comment by uiri** [comment]
You could use a hash for the inline scripts instead of a `nonce`.

**Comment by nolanlawson** [comment]
I'm going to close this because I think all of the Zeit export work (#998) shows that there's really a _lot_ you have to do to get Pinafore working as a static site.

Anybody who wants to do that is free too (as I am with Zeit), but it's way easier to just do `node server.js`, and it only has a 48MB memory overhead.
