### ISSUE TITLE
"App update available" shows too frequently

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#80]
In Firefox at least this seems to show even when there isn't actually an update. Probably I'm not detecting changes in the ServiceWorker lifecycle correctly.

**Comment by nolanlawson** [comment]
This doesn't seem to happen in Chrome or Edge, so not sure if it's something specific to Firefox's SW implementation on Android.

**Comment by nolanlawson** [comment]
On Edge this message doesn't appear to show at all. Hmmmmmm

**Comment by nolanlawson** [comment]
Related bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1456840

**Comment by wanderview** [comment]
I captured the internal file we store for the script across one of these phantom updates.  It looks like there are actually differences in the file!

Yesterday 0.2.3 script had:

const timestamp = '1524349554852'

Today it has:

const timestamp = '1524349558458'

I don't have a good explanation why other browsers wouldn't see this change, though.

**Comment by wanderview** [comment]
Note, firefox may be the only browser that defaults top level script update to always revalidate the script.  So maybe that plays into why other browsers don't see it (or as often maybe).

There is still something not quite right with the cache-control headers, though.  I think max-age=0 might help, but also there seems something wrong with the etag, etc.  Browsers aren't even attempting to revalidate right now.  I think you might need to add an Expires header if you are using etag?

**Comment by wanderview** [comment]
To test the revalidation behavior I am doing this:

1. Open a firefox private browsing tab (to ignore service worker, etc)
2. Load the service worker script URL
3. Open devtools network panel
4. Press ctrl-r to refresh

Step 4 should trigger 304 revalidations normally.

For example, try this with both:

https://pinafore.social/service-worker.js

![screenshot 2018-04-26 12 28 21](https://user-images.githubusercontent.com/1256526/39318919-6be2ed34-494d-11e8-80c8-55bc3790ec6a.png)

https://blog.wanderview.com/sw.js

![screenshot 2018-04-26 12 28 25](https://user-images.githubusercontent.com/1256526/39318928-717f89dc-494d-11e8-814b-cc61b7567ee3.png)

**Comment by nolanlawson** [comment]
Unless I'm mistaken, this is still happening somehow?

**Comment by wanderview** [comment]
I haven't seen it so far...

**Comment by nolanlawson** [comment]
Yeah my bad, it was because I was on `dev.pinafore.social` and it was legit updating very frequently because it updates whenever I push to master 😅
