### ISSUE TITLE
Here's a little theme sugestion with neutral and modern colours

### ISSUE THREAD

**Issue by Hund** [nolanlawson/pinafore#808]
I prefer neutral colours that's easy on the eyes so I made this mockup using some colours I like. :) You could replace the blue accent with other colours to get different variations of it.

I hope you like it and I would be happy if you would consider adding it. :)

![pinafore_theme](https://user-images.githubusercontent.com/320498/50040138-1a41c100-003e-11e9-8bda-cc850aac32bb.png)

**Comment by nolanlawson** [comment]
I would like to make it easier for users to create their own custom themes. :) I think this could be covered in #278, although your mockup shows me that it would also be useful if people could choose their own colors for individual buttons, as opposed to one single theme color. Thanks!
