### ISSUE TITLE
No contrast between foreground/background text on profile page with the Ozark theme

### ISSUE THREAD

**Issue by mlcdf** [nolanlawson/pinafore#82]
I guess the screenshot is pretty self-explanatory.

![image](https://user-images.githubusercontent.com/9364931/38632961-88432cfe-3dbe-11e8-9b1c-4b28f2c625f6.png)

**Comment by SpankyWorks** [comment]
There wasn't a variable in the theme SCSS for that overlay color. I added one in #84 .

**Comment by nolanlawson** [comment]
fixed by #84
