### ISSUE TITLE
viewport jumps to previously-opened reply box when scrolling

### ISSUE THREAD

**Issue by codl** [nolanlawson/pinafore#840]
1. open reply box for a toot
2. unfocus it
3. scroll up or down far enough to unload it from the virtual list
4. scroll back enough for it to be loaded again

the reply box will steal focus and the viewport will jump to it. sometimes the viewport immediately jumps back a frame later, sometimes not. not sure how to reproduce that part

i can reproduce this in chrome 71, firefox 64, and firefox for android 64

funny story, i had ran into this bug before but only looked into it now because i was backspacing in one reply box, the box got smaller by one line, which was enough to load another reply box lower down the page, which stole my keyboard focus while i was still backspacing 😓

**Comment by nolanlawson** [comment]
Thanks for the detailed repro. This is probably due to our manual focus handling.
