### ISSUE TITLE
Dark mode for the emoji picker

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#844]
The emoji picker should probably have a dark mode. Maybe we can contribute it back to `emoji-mart` in the form of a separate CSS file.

**Comment by nolanlawson** [comment]
Related: https://github.com/missive/emoji-mart/issues/293

**Comment by ndalliard** [comment]
Can be close, was merged in https://github.com/missive/emoji-mart/pull/391.
