### ISSUE TITLE
Remove unsupported native emoji from the emoji picker

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#849]
This is what it looks like in Chrome on macOS Sierra. It's pretty ugly; there may be some way to detect unknown emoji and remove them:

<img width="400" alt="screen shot 2018-12-19 at 12 21 40 pm" src="https://user-images.githubusercontent.com/283842/50246038-032a0880-0389-11e9-89bd-1204ce961ec9.png">

**Comment by nolanlawson** [comment]
Based on reading https://www.npmjs.com/package/ok-emoji it seems it would be very computationally expensive to do this, as you have to measure the rendered emoji character size :(

**Comment by nolanlawson** [comment]
Example missing emoji on macOS Sierra: https://emojipedia.org/grinning-face-with-star-eyes/

**Comment by nolanlawson** [comment]
How Halcyon does it: https://notabug.org/halcyon-suite/halcyon/src/master/assets/js/halcyon/halcyonFunctions.js#L460

We could just check one emoji (a recent one) and then fall back to Twemoji in that case.

**Comment by Fidgetcetera** [comment]
Would a potential help to this also be setting a specific option to use Twemoji, and if the user has a recent emoji fail, suggest that option to them?

**Comment by nolanlawson** [comment]
Yeah that may actually make more sense. We could detect unsupported emoji and switch to Twemoji in that case.

**Comment by nolanlawson** [comment]
done a while ago
