### ISSUE TITLE
Favorites are not paginating correctly

### ISSUE THREAD

**Issue by nspenner** [nolanlawson/pinafore#850]
The favorites timeline is not paginating past default 20-post limit. This is because the id of the last status that was retrieved is being used as the max_id in the request, but it needs to use the max_id provided in the `Link` header per the [Mastodon API](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#favourites):

> Note: max_id and since_id for next and previous pages are provided in the Link header. It is not possible to use the id of the returned objects to construct your own URLs, because the results are sorted by an internal key.

As an additional note, other routes require using the `Link` header instead of returned objects. It might be worth testing other routes to be sure they work correctly.

**Comment by nolanlawson** [comment]
Oops, so basically the favorites API works differently from every other "timeline" API? Didn't realize I had messed this up, thanks!

**Comment by nspenner** [comment]
Yeah, I only realized that it worked differently by comparing the network requests from the official Mastodon.social web app and realizing that it was sending a different `max_id`. It was difficult to find the actual documentation of the behavior, but I think the API link above has the most updated info.

**Comment by nolanlawson** [comment]
Just looked at the code, and it would be a fairly large rewrite to fix this. The assumption that we can use the last/first IDs from the timeline is littered all over the codebase. :confused:

**Comment by deutrino** [comment]
As somebody who heavily relies on favorites, this issue makes Pinafore essentially unusable for me.

**Comment by charlag** [comment]
After discussion in #1726 I had a look at how timelines work and I think the only workaround that makes sense to me is to drop offline support for favorites. Favorite ids are private which makes it hard if not impossible to cache properly. I would say that favs working online > offline favorites which don't work. I would like to ask if @nolanlawson would agree on such a workaround.

**Comment by Krinkle** [comment]
I might be experiencing the same issue. Sometimes when I open the favourites or notifications page, it remains empty or with a spinner spinning indefinitely. Then, when I switch back and forth with something else (e.g. home page) it immediately appears.

Note that I'm not using any filters on notifications or favourites (as far as I know). I'm using iOS 13.5, with Pinafore as homescreen app.
