### ISSUE TITLE
Missing template during build

### ISSUE THREAD

**Issue by pfigel** [nolanlawson/pinafore#859]
I'm trying to build Pinafore 0.16.0 with this command:

    npm run build

The command fails with the following error:

    ENOENT: no such file or directory, open '/home/pinafore/live/src/template.html'

I was able to build 0.15.0 in the same environment.

<details>
  <summary>Detailed log</summary>
  
  ```
  > pinafore@0.16.0 build /home/pinafore/live
  > cross-env NODE_ENV=production npm run build-steps


  > pinafore@0.16.0 build-steps /home/pinafore/live
  > run-s build-template-html build-third-party-assets sapper-build


  > pinafore@0.16.0 build-template-html /home/pinafore/live
  > node -r esm ./bin/build-template-html.js


  > pinafore@0.16.0 build-third-party-assets /home/pinafore/live
  > node -r esm ./bin/build-third-party-assets.js


  > pinafore@0.16.0 sapper-build /home/pinafore/live
  > sapper build

  > Building...
  > ENOENT: no such file or directory, open '/home/pinafore/live/src/template.html'
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! pinafore@0.16.0 sapper-build: `sapper build`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the pinafore@0.16.0 sapper-build script.
  ```
</details>

**Comment by nolanlawson** [comment]
I'm not able to reproduce on Ubuntu 18.04:

```bash
git clone https://github.com/nolanlawson/pinafore.git
cd pinafore
npm i
npm run build
```

It's possible that the `build-template-html` script is erroring out, but for some reason we're not seeing the error output. Could you run `npm run build-template-html` and confirm whether or not it's actually creating the `template.html` file?

**Comment by nolanlawson** [comment]
Also what is your environment? OS, node version, etc.?

**Comment by patf** [comment]
Thanks for taking a look at this! `npm run build-template-html` does not create `template.html` and has no extra log output:
```
npm run build-template-html

> pinafore@0.16.0 build-template-html /home/pinafore/live2
> node -r esm ./bin/build-template-html.js
```

This is on Debian stretch with node 8.15.0 and npm 6.5.0. I tried the same with node 10.15.0 and 11.6.0 and it produced the same result.

It *did* work on macOS with node 11.6.0 and npm 6.5.0, so it seems specific to Debian. I was able to reproduce this on a clean Debian installation with nothing other than node on it.

I did some quick debugging in `bin/build-template-html.js`. The build script enters the map loop in `buildAll()`, but stops before getting to `writeFile()`. I haven't had time to dig into it further unfortunately.

**Comment by nolanlawson** [comment]
I use Ubuntu as my main desktop, and the automated tests are running Ubuntu as well. It's odd that it would work in Ubuntu and Mac but not Debian stretch. Also the script should show an error if it runs into one.

If I had to hazard a guess, I would say that the Sass binaries failed to installed and are silently erroring for some reason.

**Comment by pfigel** [comment]
Tried this again with 1.1.0 and it works now. I suppose the switch to `yarn` could've caused the sass binaries to get rebuilt or something along those lines. Anyway, thanks again for your help!
