### ISSUE TITLE
Clicking on modal background doesn't always close modal

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pinafore#862]
The sizing of the modal images is currently not very good; it's sometimes larger than the image itself, meaning you can't actually click on the background to close the modal. There should be a way to fix this.

**Comment by spriteclad** [comment]
Any updates on this? It's starting to get really annoying for me having to go to the X every time when I want to close images.

**Comment by nolanlawson** [comment]
The update is that it still annoys me too. :) Now that we have a new image carousel, though, I can look into how to fix it.

**Comment by nolanlawson** [comment]
So it seems the only way to fix this while continuing to use `object-fit: contain` on the image is to calculate how big the image _should_ be, then report when a click is received on the area outside of it. We had to do something similar to implement focal points correctly #739.
