### ISSUE TITLE
missing custom emoji

### ISSUE THREAD

**Issue by severak** [nolanlawson/pinafore#866]
miramarco created really nice set of custom emojis - [solar system](https://blob.coffee/@miramarco/101354087597362869).

However, for some unkown reason, Saturn is missing in Pinafore. In original Mastodon it's just fine.

![screenshot_2019-01-03 tiny tilde website status](https://user-images.githubusercontent.com/615685/50660213-4b5b4480-0f9f-11e9-8949-3a564cfc0a2b.png)

**Comment by nolanlawson** [comment]
Can you try refreshing to see if it works again? Pinafore just fetches the list of custom emoji from https://blob.coffee/api/v1/custom_emojis

**Comment by severak** [comment]
still not working even after Ctrl+F5

**Comment by nolanlawson** [comment]
I'm not able to create an account at `blob.coffee`, so I cannot test this. I tried searching for that toot from the perspective of `malfunctioning.technology`, though, and it works:

![screenshot from 2019-01-13 14-32-06](https://user-images.githubusercontent.com/283842/51091483-0920c880-1740-11e9-9cac-8ed89fa8a551.png)

Not sure what's going on here, but if you can find any more info then by all means please reopen the bug. Gonna close as can't repro.
