### ISSUE TITLE
Create dark offline theme so transition from dark to offline is less jarring

### ISSUE THREAD

**Issue by zcdunn** [nolanlawson/pinafore#874]
Pinafore uses a all white theme to indicate a lack of network connection. When the user has selected a dark theme this is very jarring. Could there be a different way to indicate offline mode when using dark themes? 

Maybe relates to #531?

**Comment by nolanlawson** [comment]
You're right, there should be a "dark" offline theme.

**Comment by nolanlawson** [comment]
There is no longer a separate offline theme, so this issue can be closed
