### ISSUE TITLE
Can't mute or block from pinafore

### ISSUE THREAD

**Issue by spiritshrine** [nolanlawson/pinafore#89]
There doesn't seem to be a way to mute or block users from within the app.

**Comment by Fidgetcetera** [comment]
This is listed in #6 as a feature that needs doing still!

**Comment by nolanlawson** [comment]
Yup, not implemented yet! I'm gettin' there. :) #6 is where I track most of this stuff.

In the meantime, you can copy the permalink from the user's profile (the permalink has a little square with an arrow coming out of it) and then paste it into the search on the main mastodon web UI, and then you can block someone that way.
