### ISSUE TITLE
Alt key should be ignored by keyboard shortcuts

### ISSUE THREAD

**Issue by Vinnl** [nolanlawson/pinafore#896]
Pinafore is one of my pinned tabs, and I usually navigate to my pinned tabs using the keyboard shortcut <kbd>Alt</kbd>+\<tab number>. However, when I now switch to Pinafore (<kbd>Alt</kbd>+<kbd>4</kbd>), I can no longer switch to e.g. my calender (<kbd>Alt</kbd>+<kbd>2</kbd>), because Pinafore has hijacked that shortcut to move to my notifications within Pinafore.

**Comment by nolanlawson** [comment]
Thanks for reporting this. This appears to occur in Firefox but not Chrome. Also for the record, keyboard shortcuts can be disabled in the settings.

The proximate issue here is that we're not ignoring <kbd>Alt</kbd> presses. I'll fix that.

**Comment by Vinnl** [comment]
Thanks for the fix! I knew about the option but I like the shortcuts - I just want them in addition to my browser's ones :)
