### ISSUE TITLE
Feature Request: Custom Sharing Feature

### ISSUE THREAD

**Issue by crockwave** [nolanlawson/pinafore#986]
I created a Custom Sharing feature for the Fedilab Mastodon client for Android, to allow Mastodon content curation to content aggregation sites so that content creators can include Mastodon content in their RSS and Atom feeds.  Documentation on how that works for FediLab is here: http://teci.world/temp/fedilab_custom_sharing.pdf

In order to provide content creators resilient tools for feeding content to their subscribers, I think we need a custom sharing feature in a Mastodon web client in addition to the mobile client versions.

**Comment by nolanlawson** [comment]
Would this be covered by a "Share" feature in Pinafore? There is the [Web Share API](https://wicg.github.io/web-share/), but Pinafore does not currently use it.

Example: user taps on the "..." next to a toot, chooses "Share" and it opens up a list of other Android apps that the toot could be shared to. Per the spec, it looks like a web app is allowed to share a `text`, `title`, and `url`.

**Comment by crockwave** [comment]
This would be in addition to the Share feature.  The PDF file shows both a Share and a Custom Share feature in the toot option list.  The file also describes how it was implemented for FedLab, to be able to push RSS compatible metadata to any web site that can grab those parameters.  I develop on a Windows machine, and could try to help develop the feature if it fits your strategy

**Comment by nolanlawson** [comment]
I see, so essentially instead of using something like the Web Share API (or a built-in system share feature), it would instead call out to a remote web server and make an HTTP request to it. Is that right?

Is there a specification that describes what the server needs to implement in order to be compatible? Is this a standard RSS/Atom thing?

**Comment by crockwave** [comment]
Yes, HTTP request.  I am duplicating a Feedly Pro app Custom share feature, where you can curate from Feedly, but they limit the metadata.  The URL editing feature allows free form definition of the URL to match any server's requirement, with the variables passed by the Custom Sharing feature being matched up as best as possible to Toot object element values.  Three RSS type elements that are offered for human evaluation/editing in my Fedilab implementation are Title, Description, and Keywords.  When those are auto-populated and allowed to be edited by the content curator, you can then get some richness into the RSS feed that makes Mastodon toots very presentable in the RSS feed.

**Comment by crockwave** [comment]
**Configuration**

- Checkbox and URL text editor in Settings page
- URL can be customized to fit the specific requirements of content aggregation sites, by changing parameter values and removing unused metadata elements

If this makes sense and is appealing, I can write up a complete spec, based on what I did in Java for the Android app.  I think it is appealing for getting Mastodon curated content into content aggregation sites, to make citizen journalists be more resistant to censorship.  I also have the PHP files and MySQL table specs for creating the content add function that this Custom Sharing feature would hit, as well as the RSS/Atom feed output.  A content creator could implement a Mastodon instance, a blog, and an RSS feed on their web site, to provide full featured content.

A default Custom Sharing URL value in the Settings page could be:
http://my.site/add?name=pinafore&url=${url}&title=${title}&source=${source}&id=${id}&description=${description}&keywords=${keywords}

The only critical items in the URL template are accurately representing the metadata output by the app in the auto-generated HTTP request URL.  You could, for example, only have 3 of these 5 listed elements passed to the server, but full richness of the RSS feed is achieved when you pass all of these values.

The metadata elements output include:
- ${url} – URL to Mastodon toot
- ${title} – Title field value as auto-generated and edited in the Custom Sharing window
- ${source} – The display name of the account that created the Toot
- ${id} – The toot id
- ${description} – Description field value as auto-generated and edited in the Custom Sharing window
- ${keywords} – Keywords field value as auto-generated and edited in the Custom Sharing window

**Comment by nolanlawson** [comment]
Circling back on this, I think the best solution would be for the server that supports this functionality to implement the Web Share Target API: https://web.dev/web-share-target/ . Then Pinafore's built-in sharing functionality could share to it.

Pinafore is basically a static server with static HTML/CSS/JS files, so it itself is not a server that can accept these kinds of requests. If Mastodon instances can accept them, then that's great and Pinafore should probably support it, but this sounds like custom functionality outside of Mastodon. Please let me know if I misunderstood.
